/*
 Navicat Premium Data Transfer

 Source Server         : koneksi
 Source Server Type    : MySQL
 Source Server Version : 100413
 Source Host           : localhost:3306
 Source Schema         : stki

 Target Server Type    : MySQL
 Target Server Version : 100413
 File Encoding         : 65001

 Date: 20/10/2020 17:54:39
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for berita
-- ----------------------------
DROP TABLE IF EXISTS `berita`;
CREATE TABLE `berita`  (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `judul` tinytext CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `isi` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `url` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  INDEX `hasil`(`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 26 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of berita
-- ----------------------------
INSERT INTO `berita` VALUES (1, 'Mengenal Covid-19', 'COVID-19 adalah penyakit menular yang disebabkan oleh jenis virus corona yang baru ditemukan. Virus ini adalah virus baru dan penyakit yang tidak dikenal sebelum terjadinya wabah di Wuhan, Cina, pada bulan Desember 2019.', 'https://vivahealth.co.id/article/detail/13439/mengenal-covid-19');
INSERT INTO `berita` VALUES (2, 'Rapid test atau swab test: Apa bedanya? Mana yang lebih baik?', 'Baik tes antibodi maupun PCR memiliki jendela waktu yang optimum dalam masa inkubasi atau infeksi seseorang. Hasil tes yang mana pun perlu diperkuat dengan pemeriksaan gejala-gejala klinis serta sejarah perjalanan/kontak dengan ODP/PDP/Positif COVID-19. (Artinya, hasil tes negatif bagi seseorang yang menunjukkan gejala klinis COVID-19 atau punya sejarah kontak dengan pasien positif COVID-19 tidak bisa membebaskan dia dari protokol COVID-19)', 'https://kawalcovid19.id/content/1183/rapid-test-atau-swab-test-apa-bedanya-mana-yang-lebih-baik');
INSERT INTO `berita` VALUES (3, 'Pancasila, Sebuah Epilog (Menjawab Tantangan Zaman)', 'Kedudukan Pancasila sebagai dasar negara dan pandangan hidup bangsa telah disepakati oleh seluruh bangsa Indonesia. Notonagoro (dalam Tim MPR RI, 2013:90) mengatakan, ”lima unsur yang terdapat pada Pancasila bukanlah hal yang baru pada pembentukan Negara Indonesia, tetapi sebelumnya dan selama-lamanya telah dimiliki oleh rakyat bangsa Indonesia yang nyata ada dan hidup dalam jiwa masyarakat”. ', 'https://p4tkpknips.kemdikbud.go.id/informasi/artikel/262-pancasila-sebuah-epilog-menjawab-tantangan-zaman');
INSERT INTO `berita` VALUES (4, 'Kipin School 4.0 – Aplikasi Pendidikan Pertama yang Mendapatkan Sertifikasi TKDN (Tingkat Kandungan Dalam Negeri) di Era Covid-19', 'Sektor pendidikan adalah strategis untuk kepentingan nasional karena menyentuh 50 juta siswa oleh karena itu produk-produk jasa teknologi edukasi swasta baik wajib memiliki tingkat komponen dalam negeri (TKDN) secara maksimal untuk memenuhi aturan dan agar dana masyarakat tidak kabur ke perusahaan luar negeri dan menekan Rupiah.', 'https://pendidikan.id/news/kipin-school-4-0-aplikasi-pendidikan-pertama-yang-mendapatkan-sertifikasi-tkdn-tingkat-kandungan-dalam-negeri-di-era-covid-19/');
INSERT INTO `berita` VALUES (5, '6 Manfaat Minum Air Putih Saat Perut Kosong bagi Kesehatan', 'Manfaat minum air putih saat perut kosong terutama di pagi hari dapat menyehatkan tubuh. Tentunya kamu bisa menerapkan kebiasaan sehat yang sederhana ini setiap harinya. Apalagi, saat perut masih kosong di pagi hari, kamu harus berhati-hati untuk mengonsumsi makanan pertama yang masuk ke dalam tubuh.', 'https://hot.liputan6.com/read/4299339/6-manfaat-minum-air-putih-saat-perut-kosong-bagi-kesehatan');
INSERT INTO `berita` VALUES (6, 'Kepala BKF Sayangkan Gara-gara Administrasi Dana Penanganan Covid-19 Tak Terserap Maksimal', 'Pemerintah menganggarkan Rp 695,2 triliun sebagai dana dana penanganan Covid-19. Dari dana tersebut, sektor kesehatan mendapatkan jatah Rp 87,55 triliun. Namun dilaporkan bila anggaran di sektor kesehatan belum terserap dengan baik.', 'https://www.liputan6.com/bisnis/read/4283971/kepala-bkf-sayangkan-gara-gara-administrasi-dana-penanganan-covid-19-tak-terserap-maksimal');
INSERT INTO `berita` VALUES (7, 'Tips Mudah Manajemen Sampah Ketika di Rumah', 'Tips Mudah Manajemen Sampah Ketika di Rumah', 'https://dlh.semarangkota.go.id/tips-mudah-manajemen-sampah-ketika-di-rumah/');
INSERT INTO `berita` VALUES (8, 'Ecobricks, Solusi Cerdas Menyelamatkan Lingkungan Dari Sampah Plastik', 'Sampah plastik adalah sampah yang paling dekat dengan masyarakat, hampir disetiap kegiatan setidaknya melibatkan penggunaan plastik. Misalnya, ketika membeli minuman atau makannan dalam kemasan yang biasanya menggunakan plastik, untuk membawanya pun juga menggunakan kantong kresek yang terbuat dari plastik. Hal tersebut adalah sebagian kecil contoh sehari-hari penggunaan plastik dalam kehidupan manusia, kebiasaan yang menimbulkan tingginya angka plastik dikarenakan plastik tersebut hanya bersifat sekali pakai lalu dibuang.', 'https://dlh.semarangkota.go.id/ecobricks-solusi-cerdas-menyelamatkan-lingkungan-dari-sampah-plastik/');
INSERT INTO `berita` VALUES (9, 'Jadilah Pahlawan Lingkungan Dengan Tidak Meninggalkan Sampah Setelah Wisata Di Laut', 'Menghabiskan waktu bersama sahabat dan keluarga dengan berwisata ke pantai ataupun laut adalah hal yang menyenangkan. Akan tetapi ada satu hal yang perlu diperhatikan, yaitu tidak membuang sembarangan atau meninggalkan sampah di kawasan pantai atau laut. Pastikan untuk selalu membuang sampah pada tempatnya sebelum pergi dari lokasi wisata.', 'https://dlh.semarangkota.go.id/jadilah-pahlawan-lingkungan-dengan-tidak-meninggalkan-sampah-setelah-wisata-di-laut/');
INSERT INTO `berita` VALUES (10, 'Penanggulangan Sampah Plastik di Laut Indonesia yang Efektif', 'Penanggulangan sampah plastik di Laut Indonesia – Sampah plastik yang ada di Laut Indonesia semakin meningkat. Hal itu dikarenakan pembuangan sampah di sungai semakin meningkat. Sampah yang dibuang di sungai tersebut nantinya akan sampai ke laut sehingga laut pun akan menjadi kotor dipenuhi oleh sampah. Sampai saat ini pemerintah Indonesia belum tahu penanggulangan yang efektif dan efisien. Meskipun beberapa cara telah dicoba, namun tetap saja volume sampah di laut Indonesia semakin meningkat.', 'https://dlh.semarangkota.go.id/penanggulangan-sampah-plastik-di-laut-indonesia-yang-efektif/');
INSERT INTO `berita` VALUES (11, 'Penggunaan Teknologi Pengolahan Sampah', 'Teknologi pengolahan sampah sangat berpengaruh bagi kenyamanan dan kesehatan manusia. Bagaimana suatu daerah atau tempat menerapkan teknologi pengolahan sampah ini dengan tepat guna dan sebaik-baiknya.Seperti yang kita ketahui dan kita rasakan, sampah yang dibuang begitu saja tentunya akan mencemari lingkungan hidup. Menimbukan efek tidak nyaman, bahkan efek serius yang mungkin ditumbulkan seperti datangnya pencakit dan keracunan. Untuk itu, sangat dibutuhkan adanya penerapan dan penggunaan teknologi pengolahan sampah.', 'https://dlh.semarangkota.go.id/penggunaan-teknologi-pengolahan-sampah/');
INSERT INTO `berita` VALUES (12, '5 Cara Pembuatan Pupuk Kompos dari Sampah Bekas yang Mudah', 'Pembuatan pupuk kompos dari sampah bekas – Setiap rumah tangga pasti menghasilkan limbah baik itu limbah organik maupun limbah anorganik. Berbagai macam bentuk limbah  pun dihasilkan mulai dari yang cair maupun yang padat. Jika limbah tersebut tidak diolah dengan baik bisa mencemari lingkungan sehingga diperlukan pengolahan limbah yang baik dan benar. Salah satu pengolahan limbah yang sering dilakukan oleh masyarakat adalah pembuatan pupuk kompos.  Sampah yang tadinya tidak berguna bisa diubah menjadi pupuk kompos yang lebih berguna.', 'https://dlh.semarangkota.go.id/5-cara-pembuatan-pupuk-kompos-dari-sampah-bekas-yang-mudah/');
INSERT INTO `berita` VALUES (13, 'Konservasi Air Dengan Lubang Resapan Biopori dan Sumur Resapan', 'Kota Semarang memiliki keunikan dan daya tarik tersendiri dikarenakan letak topografinya yang memiliki wilayah perbukitan dan dataran rendah, yang tidak dimiliki oleh Ibu kota Provinsi lain di Pulau Jawa. Wilayah Kota Semarang dengan perbukitannya (bagian atas) merupakan wilayah yang memiliki cadangan air bersih yang memadai untuk memenuhi kebutuhan warga Kota Semarang, sedangkan pada wilayah dataran rendah yang sebagian besar merupakan wilayah pesisir merupakan pusat perekonomian kota.  Wilayah perbukitan sebagai penyimpan dan penyedia sumberdaya air bersih di Kota Semarang, saat ini mulai berkembang menjadi pusat kegiatan perekonomian bagi Kota Semarang.', 'https://dlh.semarangkota.go.id/konservasi-air-dengan-lubang-resapan-biopori-dan-sumur-resapan/');
INSERT INTO `berita` VALUES (14, 'Penting 5 Manfaat Menjaga Kebersihan', 'Manfaat menjaga kebersihan adalah sebagian dari iman, itulah salah satu hadits yang harus dijadikan pedoman oleh umat islam, dimana jika ingin beriman dia juga harus memelihara kebersihan. Lingkungan yang bersih adalah dambaan semua warga. Dengan bersih, mereka dapat menjalani aktivitas sehari-hari dengan aman dan nyaman.', 'https://dlh.semarangkota.go.id/penting-5-manfaat-menjaga-kebersihan/');
INSERT INTO `berita` VALUES (15, 'Hari Harimau Sedunia (Global Tiger Day) 29 Juli', 'Sejarah dicetuskannya tanggal tersebut diputuskan dalam International Tiger Summit atau Konferensi Tingkat Tinggi (KTT) Harimau Internasional pertama pada 2010 di St. Petersburg, Rusia. Indonesia turut serta dalam momen penting ini.', 'https://dlhk.acehprov.go.id/2020/07/hari-harimau-sedunia-global-tiger-day-29-juli/');
INSERT INTO `berita` VALUES (16, '5 Kemajuan Penemuan Ilmiah dan Teknologi yang Dapat Ubah Masa Depan', 'Dunia penelitian aktivitas ilmiah memang rumit untuk dipahami. Seseorang bahkan tak mau berurusan dengan hal itu. Sebab, terkesan sulit dan menghabiskan waktu. Namun, penelitian sangat penting bagi kelangsungan hidup manusia.', 'https://www.liputan6.com/global/read/4321155/5-kemajuan-penemuan-ilmiah-dan-teknologi-yang-dapat-ubah-masa-depan');
INSERT INTO `berita` VALUES (17, 'Generasi Muda Jadi Pionir Penggunaan Teknologi Guna Genjot Produktivitas', 'Salah satu hikmah dibalik pandemi Covid-19 adalah gencarnya penggunaan berbagai aplikasi berbasis daring. Kementerian Komunikasi dan Informatika (Kemkominfo) mencatat, penggunaan aplikasi daring naik 432 persen selama Covid-19.', 'https://www.liputan6.com/bisnis/read/4276587/generasi-muda-jadi-pionir-penggunaan-teknologi-guna-genjot-produktivitas');
INSERT INTO `berita` VALUES (18, 'Hari Lingkungan Hidup Sedunia, Ketahui 5 Cara Teknologi Lindungi Keanekaragaman Hayati', 'Mendorong publik menjaga lingkungan dengan berbagai tantangan yang tengah dihadapi, Hari Lingkungan Hidup Sedunia telah secara konsisten diperangati setiap 5 Juni. Melansir dari laman resminya, Sabtu (6/6/2020) keanekaragaman hayati jadi satu fokus yang diangkat tahun ini.', 'https://www.liputan6.com/lifestyle/read/4272302/hari-lingkungan-hidup-sedunia-ketahui-5-cara-teknologi-lindungi-keanekaragaman-hayati');
INSERT INTO `berita` VALUES (19, 'Orangtua Perlu Mendampingi Anak Belajar', 'Peran orang tua dalam mendidik anak memang nomor satu. Sebelum anak mengenal dunia luar, orang pertama yang ia kenal adalah ayah dan ibunya. Anak akan selalu meniru apa yang dibuat  dari kedua orang tuanya. Apa yang ia dengar dan lihat, itulah yang dia tangkap dan simpan di memorinya. Pertama kali dia belajar bicara, orang tua adalah guru baginya.', 'https://www.kompasiana.com/lesley/5f7c5f81e95df71af41e2ae2/orang-tua-perlu-mendampingi-anak-belajar');
INSERT INTO `berita` VALUES (20, 'EFEKTIVITAS PEMBELAJARAN DARING DI MASA PANDEMI COVID-19', 'Sebagai upaya untuk mencegah pandemi Covid-19, pemerintah mengeluarkan kebijakan agar sekolah-sekolah meminta siswanya untuk belajar di rumah. Mulai 16 Maret 2020 sekolah menerapkan metode pembelajaran siswa secara daring. Lalu, efektifkah pembelajaran daring ini?', 'https://bdkjakarta.kemenag.go.id/berita/efektivitas-pembelajaran-daring-di-masa-pandemi-covid-19');
INSERT INTO `berita` VALUES (21, 'TEKNOLOGI PENDIDIKAN ERA DIGITAL DAN TANTANGAN INDONESIA MENGHADAPI DINAMIKA PERADABAN MILENIUM SEBAGAI ERA ROBOTIC', 'DAMPAK PANDEMIK TERHADAP SISTEM PENDIDIKAN SAAT INI.\r\nKita saat ini masuk kepada era revolusi industry 4.0,era serba digital dalam segala hal,mulai dari urusan dapur sampai urusan pendidikan dan pelayanan dalam segala hal,di bidang transformasi yang serba online,tidak ada lagi yang dinamakan susah dan sulit semua teknologi menawarkan fasilitas yang serba mudah dan memungkinkan. Begitu juga penulis kedudukan sebagai narasumber,sebagai fasilitator dan sebagai penulis,dimudahkan dengan hadirnya teknologi, juga sebagai arsiteknya di bidang pendidikan harus cepat beradaptasi dan cepat menguasai ilmu pengetahuan yang sudah berubah situasi dan kondisinya, widyaiswara tidak lagi menunggu jadwal mengajar secara klasikal tapi di tuntut untuk lebih pro aktif dalam beraktifitas dan berperan,harus mampu merubah mindset,pola pikiran kita yang klasik menjadi digital. Misalnya tahun tahun sebelumnya widyaiswara keahliannya dalam mentransfer sikap ,pengetahuan dan keahlian di kelas secara klasikal,bertatap muka secara langsung dengan para peserta,menyampaikan materi dalam bentuk slide ,bisa bersalaman secara langsung,bertanya secara langsung dan memberikan senyuman dan tawa serta canda secara alami', 'https://bdkjakarta.kemenag.go.id/berita/teknologi-pendidikan-era-digital-dan-tantangan-indonesia-menghadapi-dinamika-peradaban-milenium-sebagai-era-robotic');
INSERT INTO `berita` VALUES (22, 'Hubungan Antara DILAN (Pendidikan Dalam Jaringan) dan MILEA (Milennial Era) Pada Masa Pandemi COVID-19', 'Indonesia dan banyak Negara di dunia tahun ini tengah mengalami musibah besar, berupa penyakit yang disebabkan oleh virus jenis baru yang dikenal dengan istilah COVID-19 (Corona Virus Diseases). Virus Corona membuat aktivitas manusia berubah total untuk beberapa minggu bahkan bulan. Perubahan ini terjadi pada banyak aspek, mulai dari aktivitas perekonomian, industri, sosial, bahkan pendidikan.', 'https://bdkjakarta.kemenag.go.id/berita/hubungan-antara-dilan-pendidikan-dalam-jaringan-dan-milea-milennial-era-pada-masa-pandemi-covid-19');
INSERT INTO `berita` VALUES (23, 'Peran Pemerintah Dalam Membangun Budaya Literasi Indonesia', 'Akhir tahun lalu, tepatnya tanggal 3 Desember 2019, hasil studi Program for International Student Assessment (PISA) 2018 telah dirilis. PISA adalah sebuah sistem ujian yang dilakukan oleh Organization for Economics Cooperation and Development (OECD) untuk mengukur kualitas hasil pendidikan dari negara-negara di seluruh dunia. Setiap tiga tahun sekali PISA melakukan tes kemampuan membaca, matematika, dan sains terhadap siswa berusia 15 tahun yang dipilih secara acak dari berbagai negara. Negara yang diuji pada tahun 2018 berjumlah 78 negara, lebih banyak dari studi yang sama tahun 2015 yang diikuti oleh 72 negara.', 'https://bdkjakarta.kemenag.go.id/berita/peran-pemerintah-dalam-membangun-budaya-literasi-indonesia');
INSERT INTO `berita` VALUES (24, 'SELAMATKAN GENERASI EMAS INDONESIA', 'Generasi muda adalah aset yang akan membawa kemajuan suatu bangsa. Berdasarkan hasil Survei Penduduk Antar Sensus (SUPAS) 2015, jumlah penduduk Indonesia pada 2045 diprediksi mencapai 318,96 juta jiwa. Jumlah tersebut terdiri dari 160,21 juta jiwa perempuan dan 158,75 juta jiwa laki-laki. Sementara jumlah penduduk tahun 2019 sudah mencapai 266,91 juta jiwa, yang berarti akan bertambah 52,05 juta jiwa dalam 26 tahun ke depan.', 'https://bdkjakarta.kemenag.go.id/berita/selamatkan-generasi-emas-indonesia');
INSERT INTO `berita` VALUES (25, 'RESTART BUMI ALA COVID-19', 'Yup, diawal tahun 2020 ini, bumi merestart dirinya karena covid 19. Salah satunya kualitas udara di berbagai kota didunia, seperti diungkapkan oleh berbagai media sosial. Salah satunya NASA membagikan hasil citra satelit, yang mengungkapkan udara di China sebelum dan sesudah wabah covid melanda China.', 'https://bdkjakarta.kemenag.go.id/berita/restart-bumi-ala-covid-19');

-- ----------------------------
-- Table structure for stopword
-- ----------------------------
DROP TABLE IF EXISTS `stopword`;
CREATE TABLE `stopword`  (
  `stopword` varchar(25) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL
) ENGINE = MyISAM CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of stopword
-- ----------------------------
INSERT INTO `stopword` VALUES ('ada');
INSERT INTO `stopword` VALUES ('adalah');
INSERT INTO `stopword` VALUES ('adanya');
INSERT INTO `stopword` VALUES ('adapun');
INSERT INTO `stopword` VALUES ('agak');
INSERT INTO `stopword` VALUES ('agaknya');
INSERT INTO `stopword` VALUES ('agar');
INSERT INTO `stopword` VALUES ('akan');
INSERT INTO `stopword` VALUES ('akankah');
INSERT INTO `stopword` VALUES ('akhir');
INSERT INTO `stopword` VALUES ('akhiri');
INSERT INTO `stopword` VALUES ('akhirnya');
INSERT INTO `stopword` VALUES ('aku');
INSERT INTO `stopword` VALUES ('akulah');
INSERT INTO `stopword` VALUES ('amat');
INSERT INTO `stopword` VALUES ('amatlah');
INSERT INTO `stopword` VALUES ('anda');
INSERT INTO `stopword` VALUES ('andalah');
INSERT INTO `stopword` VALUES ('antar');
INSERT INTO `stopword` VALUES ('antara');
INSERT INTO `stopword` VALUES ('antaranya');
INSERT INTO `stopword` VALUES ('apa');
INSERT INTO `stopword` VALUES ('apaan');
INSERT INTO `stopword` VALUES ('apabila');
INSERT INTO `stopword` VALUES ('apakah');
INSERT INTO `stopword` VALUES ('apalagi');
INSERT INTO `stopword` VALUES ('apatah');
INSERT INTO `stopword` VALUES ('artinya');
INSERT INTO `stopword` VALUES ('asal');
INSERT INTO `stopword` VALUES ('asalkan');
INSERT INTO `stopword` VALUES ('atas');
INSERT INTO `stopword` VALUES ('atau');
INSERT INTO `stopword` VALUES ('ataukah');
INSERT INTO `stopword` VALUES ('ataupun');
INSERT INTO `stopword` VALUES ('awal');
INSERT INTO `stopword` VALUES ('awalnya');
INSERT INTO `stopword` VALUES ('bagai');
INSERT INTO `stopword` VALUES ('bagaikan');
INSERT INTO `stopword` VALUES ('bagaimana');
INSERT INTO `stopword` VALUES ('bagaimanakah');
INSERT INTO `stopword` VALUES ('bagaimanapun');
INSERT INTO `stopword` VALUES ('bagi');
INSERT INTO `stopword` VALUES ('bagian');
INSERT INTO `stopword` VALUES ('bahkan');
INSERT INTO `stopword` VALUES ('bahwa');
INSERT INTO `stopword` VALUES ('bahwasanya');
INSERT INTO `stopword` VALUES ('baik');
INSERT INTO `stopword` VALUES ('baiknya');
INSERT INTO `stopword` VALUES ('bakal');
INSERT INTO `stopword` VALUES ('bakalan');
INSERT INTO `stopword` VALUES ('balik');
INSERT INTO `stopword` VALUES ('banyak');
INSERT INTO `stopword` VALUES ('bapak');
INSERT INTO `stopword` VALUES ('baru');
INSERT INTO `stopword` VALUES ('bawah');
INSERT INTO `stopword` VALUES ('beberapa');
INSERT INTO `stopword` VALUES ('begini');
INSERT INTO `stopword` VALUES ('beginian');
INSERT INTO `stopword` VALUES ('beginikah');
INSERT INTO `stopword` VALUES ('beginilah');
INSERT INTO `stopword` VALUES ('begitu');
INSERT INTO `stopword` VALUES ('begitukah');
INSERT INTO `stopword` VALUES ('begitulah');
INSERT INTO `stopword` VALUES ('begitupun');
INSERT INTO `stopword` VALUES ('bekerja');
INSERT INTO `stopword` VALUES ('belakang');
INSERT INTO `stopword` VALUES ('belakangan');
INSERT INTO `stopword` VALUES ('belum');
INSERT INTO `stopword` VALUES ('belumlah');
INSERT INTO `stopword` VALUES ('benar');
INSERT INTO `stopword` VALUES ('benarkah');
INSERT INTO `stopword` VALUES ('benarlah');
INSERT INTO `stopword` VALUES ('berada');
INSERT INTO `stopword` VALUES ('berakhir');
INSERT INTO `stopword` VALUES ('berakhirlah');
INSERT INTO `stopword` VALUES ('berakhirnya');
INSERT INTO `stopword` VALUES ('berapa');
INSERT INTO `stopword` VALUES ('berapakah');
INSERT INTO `stopword` VALUES ('berapalah');
INSERT INTO `stopword` VALUES ('berapapun');
INSERT INTO `stopword` VALUES ('berarti');
INSERT INTO `stopword` VALUES ('berawal');
INSERT INTO `stopword` VALUES ('berbagai');
INSERT INTO `stopword` VALUES ('berdatangan');
INSERT INTO `stopword` VALUES ('beri');
INSERT INTO `stopword` VALUES ('berikan');
INSERT INTO `stopword` VALUES ('berikut');
INSERT INTO `stopword` VALUES ('berikutnya');
INSERT INTO `stopword` VALUES ('berjumlah');
INSERT INTO `stopword` VALUES ('berkali');
INSERT INTO `stopword` VALUES ('berkata');
INSERT INTO `stopword` VALUES ('berkehendak');
INSERT INTO `stopword` VALUES ('berkeinginan');
INSERT INTO `stopword` VALUES ('berkenaan');
INSERT INTO `stopword` VALUES ('berlainan');
INSERT INTO `stopword` VALUES ('berlalu');
INSERT INTO `stopword` VALUES ('berlangsung');
INSERT INTO `stopword` VALUES ('berlebihan');
INSERT INTO `stopword` VALUES ('bermacam');
INSERT INTO `stopword` VALUES ('bermaksud');
INSERT INTO `stopword` VALUES ('bermula');
INSERT INTO `stopword` VALUES ('bersama');
INSERT INTO `stopword` VALUES ('bersiap');
INSERT INTO `stopword` VALUES ('bertanya');
INSERT INTO `stopword` VALUES ('berturut');
INSERT INTO `stopword` VALUES ('bertutur');
INSERT INTO `stopword` VALUES ('berujar');
INSERT INTO `stopword` VALUES ('berupa');
INSERT INTO `stopword` VALUES ('besar');
INSERT INTO `stopword` VALUES ('betul');
INSERT INTO `stopword` VALUES ('betulkah');
INSERT INTO `stopword` VALUES ('biasa');
INSERT INTO `stopword` VALUES ('biasanya');
INSERT INTO `stopword` VALUES ('bila');
INSERT INTO `stopword` VALUES ('bilakah');
INSERT INTO `stopword` VALUES ('bisa');
INSERT INTO `stopword` VALUES ('bisakah');
INSERT INTO `stopword` VALUES ('boleh');
INSERT INTO `stopword` VALUES ('bolehkah');
INSERT INTO `stopword` VALUES ('bolehlah');
INSERT INTO `stopword` VALUES ('buat');
INSERT INTO `stopword` VALUES ('bukan');
INSERT INTO `stopword` VALUES ('bukankah');
INSERT INTO `stopword` VALUES ('bukanlah');
INSERT INTO `stopword` VALUES ('bukannya');
INSERT INTO `stopword` VALUES ('bulan');
INSERT INTO `stopword` VALUES ('bung');
INSERT INTO `stopword` VALUES ('cara');
INSERT INTO `stopword` VALUES ('caranya');
INSERT INTO `stopword` VALUES ('cukup');
INSERT INTO `stopword` VALUES ('cukupkah');
INSERT INTO `stopword` VALUES ('cukuplah');
INSERT INTO `stopword` VALUES ('cuma');
INSERT INTO `stopword` VALUES ('dahulu');
INSERT INTO `stopword` VALUES ('dalam');
INSERT INTO `stopword` VALUES ('dan');
INSERT INTO `stopword` VALUES ('dapat');
INSERT INTO `stopword` VALUES ('dari');
INSERT INTO `stopword` VALUES ('daripada');
INSERT INTO `stopword` VALUES ('datang');
INSERT INTO `stopword` VALUES ('dekat');
INSERT INTO `stopword` VALUES ('demi');
INSERT INTO `stopword` VALUES ('demikian');
INSERT INTO `stopword` VALUES ('demikianlah');
INSERT INTO `stopword` VALUES ('dengan');
INSERT INTO `stopword` VALUES ('depan');
INSERT INTO `stopword` VALUES ('di');
INSERT INTO `stopword` VALUES ('dia');
INSERT INTO `stopword` VALUES ('diakhiri');
INSERT INTO `stopword` VALUES ('diakhirinya');
INSERT INTO `stopword` VALUES ('dialah');
INSERT INTO `stopword` VALUES ('diantara');
INSERT INTO `stopword` VALUES ('diantaranya');
INSERT INTO `stopword` VALUES ('diberi');
INSERT INTO `stopword` VALUES ('diberikan');
INSERT INTO `stopword` VALUES ('diberikannya');
INSERT INTO `stopword` VALUES ('dibuat');
INSERT INTO `stopword` VALUES ('dibuatnya');
INSERT INTO `stopword` VALUES ('didapat');
INSERT INTO `stopword` VALUES ('didatangkan');
INSERT INTO `stopword` VALUES ('digunakan');
INSERT INTO `stopword` VALUES ('diibaratkan');
INSERT INTO `stopword` VALUES ('diibaratkannya');
INSERT INTO `stopword` VALUES ('diingat');
INSERT INTO `stopword` VALUES ('diingatkan');
INSERT INTO `stopword` VALUES ('diinginkan');
INSERT INTO `stopword` VALUES ('dijawab');
INSERT INTO `stopword` VALUES ('dijelaskan');
INSERT INTO `stopword` VALUES ('dijelaskannya');
INSERT INTO `stopword` VALUES ('dikarenakan');
INSERT INTO `stopword` VALUES ('dikatakan');
INSERT INTO `stopword` VALUES ('dikatakannya');
INSERT INTO `stopword` VALUES ('dikerjakan');
INSERT INTO `stopword` VALUES ('diketahui');
INSERT INTO `stopword` VALUES ('diketahuinya');
INSERT INTO `stopword` VALUES ('dikira');
INSERT INTO `stopword` VALUES ('dilakukan');
INSERT INTO `stopword` VALUES ('dilalui');
INSERT INTO `stopword` VALUES ('dilihat');
INSERT INTO `stopword` VALUES ('dimaksud');
INSERT INTO `stopword` VALUES ('dimaksudkan');
INSERT INTO `stopword` VALUES ('dimaksudkannya');
INSERT INTO `stopword` VALUES ('dimaksudnya');
INSERT INTO `stopword` VALUES ('diminta');
INSERT INTO `stopword` VALUES ('dimintai');
INSERT INTO `stopword` VALUES ('dimisalkan');
INSERT INTO `stopword` VALUES ('dimulai');
INSERT INTO `stopword` VALUES ('dimulailah');
INSERT INTO `stopword` VALUES ('dimulainya');
INSERT INTO `stopword` VALUES ('dimungkinkan');
INSERT INTO `stopword` VALUES ('dini');
INSERT INTO `stopword` VALUES ('dipastikan');
INSERT INTO `stopword` VALUES ('diperbuat');
INSERT INTO `stopword` VALUES ('diperbuatnya');
INSERT INTO `stopword` VALUES ('dipergunakan');
INSERT INTO `stopword` VALUES ('diperkirakan');
INSERT INTO `stopword` VALUES ('diperlihatkan');
INSERT INTO `stopword` VALUES ('diperlukan');
INSERT INTO `stopword` VALUES ('diperlukannya');
INSERT INTO `stopword` VALUES ('dipersoalkan');
INSERT INTO `stopword` VALUES ('dipertanyakan');
INSERT INTO `stopword` VALUES ('dipunyai');
INSERT INTO `stopword` VALUES ('diri');
INSERT INTO `stopword` VALUES ('dirinya');
INSERT INTO `stopword` VALUES ('disampaikan');
INSERT INTO `stopword` VALUES ('disebut');
INSERT INTO `stopword` VALUES ('disebutkan');
INSERT INTO `stopword` VALUES ('disebutkannya');
INSERT INTO `stopword` VALUES ('disini');
INSERT INTO `stopword` VALUES ('disinilah');
INSERT INTO `stopword` VALUES ('ditambahkan');
INSERT INTO `stopword` VALUES ('ditandaskan');
INSERT INTO `stopword` VALUES ('ditanya');
INSERT INTO `stopword` VALUES ('ditanyai');
INSERT INTO `stopword` VALUES ('ditanyakan');
INSERT INTO `stopword` VALUES ('ditegaskan');
INSERT INTO `stopword` VALUES ('ditujukan');
INSERT INTO `stopword` VALUES ('ditunjuk');
INSERT INTO `stopword` VALUES ('ditunjuki');
INSERT INTO `stopword` VALUES ('ditunjukkan');
INSERT INTO `stopword` VALUES ('ditunjukkannya');
INSERT INTO `stopword` VALUES ('ditunjuknya');
INSERT INTO `stopword` VALUES ('dituturkan');
INSERT INTO `stopword` VALUES ('dituturkannya');
INSERT INTO `stopword` VALUES ('diucapkan');
INSERT INTO `stopword` VALUES ('diucapkannya');
INSERT INTO `stopword` VALUES ('diungkapkan');
INSERT INTO `stopword` VALUES ('dong');
INSERT INTO `stopword` VALUES ('dua');
INSERT INTO `stopword` VALUES ('dulu');
INSERT INTO `stopword` VALUES ('empat');
INSERT INTO `stopword` VALUES ('enggak');
INSERT INTO `stopword` VALUES ('enggaknya');
INSERT INTO `stopword` VALUES ('entah');
INSERT INTO `stopword` VALUES ('entahlah');
INSERT INTO `stopword` VALUES ('guna');
INSERT INTO `stopword` VALUES ('gunakan');
INSERT INTO `stopword` VALUES ('hal');
INSERT INTO `stopword` VALUES ('hampir');
INSERT INTO `stopword` VALUES ('hanya');
INSERT INTO `stopword` VALUES ('hanyalah');
INSERT INTO `stopword` VALUES ('hari');
INSERT INTO `stopword` VALUES ('harus');
INSERT INTO `stopword` VALUES ('haruslah');
INSERT INTO `stopword` VALUES ('harusnya');
INSERT INTO `stopword` VALUES ('hendak');
INSERT INTO `stopword` VALUES ('hendaklah');
INSERT INTO `stopword` VALUES ('hendaknya');
INSERT INTO `stopword` VALUES ('hingga');
INSERT INTO `stopword` VALUES ('ia');
INSERT INTO `stopword` VALUES ('ialah');
INSERT INTO `stopword` VALUES ('ibarat');
INSERT INTO `stopword` VALUES ('ibaratkan');
INSERT INTO `stopword` VALUES ('ibaratnya');
INSERT INTO `stopword` VALUES ('ibu');
INSERT INTO `stopword` VALUES ('ikut');
INSERT INTO `stopword` VALUES ('ingat');
INSERT INTO `stopword` VALUES ('ingin');
INSERT INTO `stopword` VALUES ('inginkah');
INSERT INTO `stopword` VALUES ('inginkan');
INSERT INTO `stopword` VALUES ('ini');
INSERT INTO `stopword` VALUES ('inikah');
INSERT INTO `stopword` VALUES ('inilah');
INSERT INTO `stopword` VALUES ('itu');
INSERT INTO `stopword` VALUES ('itukah');
INSERT INTO `stopword` VALUES ('itulah');
INSERT INTO `stopword` VALUES ('jadi');
INSERT INTO `stopword` VALUES ('jadilah');
INSERT INTO `stopword` VALUES ('jadinya');
INSERT INTO `stopword` VALUES ('jangan');
INSERT INTO `stopword` VALUES ('jangankan');
INSERT INTO `stopword` VALUES ('janganlah');
INSERT INTO `stopword` VALUES ('jauh');
INSERT INTO `stopword` VALUES ('jawab');
INSERT INTO `stopword` VALUES ('jawaban');
INSERT INTO `stopword` VALUES ('jawabnya');
INSERT INTO `stopword` VALUES ('jelas');
INSERT INTO `stopword` VALUES ('jelaskan');
INSERT INTO `stopword` VALUES ('jelaslah');
INSERT INTO `stopword` VALUES ('jelasnya');
INSERT INTO `stopword` VALUES ('jika');
INSERT INTO `stopword` VALUES ('jikalau');
INSERT INTO `stopword` VALUES ('juga');
INSERT INTO `stopword` VALUES ('jumlah');
INSERT INTO `stopword` VALUES ('jumlahnya');
INSERT INTO `stopword` VALUES ('justru');
INSERT INTO `stopword` VALUES ('kala');
INSERT INTO `stopword` VALUES ('kalau');
INSERT INTO `stopword` VALUES ('kalaulah');
INSERT INTO `stopword` VALUES ('kalaupun');
INSERT INTO `stopword` VALUES ('kali');
INSERT INTO `stopword` VALUES ('kalian');
INSERT INTO `stopword` VALUES ('kami');
INSERT INTO `stopword` VALUES ('kamilah');
INSERT INTO `stopword` VALUES ('kamu');
INSERT INTO `stopword` VALUES ('kamulah');
INSERT INTO `stopword` VALUES ('kan');
INSERT INTO `stopword` VALUES ('kapan');
INSERT INTO `stopword` VALUES ('kapankah');
INSERT INTO `stopword` VALUES ('kapanpun');
INSERT INTO `stopword` VALUES ('karena');
INSERT INTO `stopword` VALUES ('karenanya');
INSERT INTO `stopword` VALUES ('kasus');
INSERT INTO `stopword` VALUES ('kata');
INSERT INTO `stopword` VALUES ('katakan');
INSERT INTO `stopword` VALUES ('katakanlah');
INSERT INTO `stopword` VALUES ('katanya');
INSERT INTO `stopword` VALUES ('ke');
INSERT INTO `stopword` VALUES ('keadaan');
INSERT INTO `stopword` VALUES ('kebetulan');
INSERT INTO `stopword` VALUES ('kecil');
INSERT INTO `stopword` VALUES ('kedua');
INSERT INTO `stopword` VALUES ('keduanya');
INSERT INTO `stopword` VALUES ('keinginan');
INSERT INTO `stopword` VALUES ('kelamaan');
INSERT INTO `stopword` VALUES ('kelihatan');
INSERT INTO `stopword` VALUES ('kelihatannya');
INSERT INTO `stopword` VALUES ('kelima');
INSERT INTO `stopword` VALUES ('keluar');
INSERT INTO `stopword` VALUES ('kembali');
INSERT INTO `stopword` VALUES ('kemudian');
INSERT INTO `stopword` VALUES ('kemungkinan');
INSERT INTO `stopword` VALUES ('kemungkinannya');
INSERT INTO `stopword` VALUES ('kenapa');
INSERT INTO `stopword` VALUES ('kepada');
INSERT INTO `stopword` VALUES ('kepadanya');
INSERT INTO `stopword` VALUES ('kesampaian');
INSERT INTO `stopword` VALUES ('keseluruhan');
INSERT INTO `stopword` VALUES ('keseluruhannya');
INSERT INTO `stopword` VALUES ('keterlaluan');
INSERT INTO `stopword` VALUES ('ketika');
INSERT INTO `stopword` VALUES ('khususnya');
INSERT INTO `stopword` VALUES ('kini');
INSERT INTO `stopword` VALUES ('kinilah');
INSERT INTO `stopword` VALUES ('kira');
INSERT INTO `stopword` VALUES ('kiranya');
INSERT INTO `stopword` VALUES ('kita');
INSERT INTO `stopword` VALUES ('kitalah');
INSERT INTO `stopword` VALUES ('kok');
INSERT INTO `stopword` VALUES ('kurang');
INSERT INTO `stopword` VALUES ('kurangnya');
INSERT INTO `stopword` VALUES ('lagi');
INSERT INTO `stopword` VALUES ('lagian');
INSERT INTO `stopword` VALUES ('lah');
INSERT INTO `stopword` VALUES ('lain');
INSERT INTO `stopword` VALUES ('lainnya');
INSERT INTO `stopword` VALUES ('lalu');
INSERT INTO `stopword` VALUES ('lama');
INSERT INTO `stopword` VALUES ('lamanya');
INSERT INTO `stopword` VALUES ('lanjut');
INSERT INTO `stopword` VALUES ('lanjutnya');
INSERT INTO `stopword` VALUES ('lebih');
INSERT INTO `stopword` VALUES ('lewat');
INSERT INTO `stopword` VALUES ('lima');
INSERT INTO `stopword` VALUES ('luar');
INSERT INTO `stopword` VALUES ('macam');
INSERT INTO `stopword` VALUES ('maka');
INSERT INTO `stopword` VALUES ('makanya');
INSERT INTO `stopword` VALUES ('makin');
INSERT INTO `stopword` VALUES ('malah');
INSERT INTO `stopword` VALUES ('malahan');
INSERT INTO `stopword` VALUES ('mampu');
INSERT INTO `stopword` VALUES ('mampukah');
INSERT INTO `stopword` VALUES ('mana');
INSERT INTO `stopword` VALUES ('manakala');
INSERT INTO `stopword` VALUES ('manalagi');
INSERT INTO `stopword` VALUES ('masa');
INSERT INTO `stopword` VALUES ('masalah');
INSERT INTO `stopword` VALUES ('masalahnya');
INSERT INTO `stopword` VALUES ('masih');
INSERT INTO `stopword` VALUES ('masihkah');
INSERT INTO `stopword` VALUES ('masing');
INSERT INTO `stopword` VALUES ('mata');
INSERT INTO `stopword` VALUES ('mau');
INSERT INTO `stopword` VALUES ('maupun');
INSERT INTO `stopword` VALUES ('melainkan');
INSERT INTO `stopword` VALUES ('melakukan');
INSERT INTO `stopword` VALUES ('melalui');
INSERT INTO `stopword` VALUES ('melihat');
INSERT INTO `stopword` VALUES ('melihatnya');
INSERT INTO `stopword` VALUES ('memang');
INSERT INTO `stopword` VALUES ('memastikan');
INSERT INTO `stopword` VALUES ('memberi');
INSERT INTO `stopword` VALUES ('memberikan');
INSERT INTO `stopword` VALUES ('membuat');
INSERT INTO `stopword` VALUES ('memerlukan');
INSERT INTO `stopword` VALUES ('memihak');
INSERT INTO `stopword` VALUES ('meminta');
INSERT INTO `stopword` VALUES ('memintakan');
INSERT INTO `stopword` VALUES ('memisalkan');
INSERT INTO `stopword` VALUES ('memperbuat');
INSERT INTO `stopword` VALUES ('mempergunakan');
INSERT INTO `stopword` VALUES ('memperkirakan');
INSERT INTO `stopword` VALUES ('memperlihatkan');
INSERT INTO `stopword` VALUES ('mempersiapkan');
INSERT INTO `stopword` VALUES ('mempersoalkan');
INSERT INTO `stopword` VALUES ('mempertanyakan');
INSERT INTO `stopword` VALUES ('mempunyai');
INSERT INTO `stopword` VALUES ('memulai');
INSERT INTO `stopword` VALUES ('memungkinkan');
INSERT INTO `stopword` VALUES ('menaiki');
INSERT INTO `stopword` VALUES ('menambahkan');
INSERT INTO `stopword` VALUES ('menandaskan');
INSERT INTO `stopword` VALUES ('menanti');
INSERT INTO `stopword` VALUES ('menantikan');
INSERT INTO `stopword` VALUES ('menanya');
INSERT INTO `stopword` VALUES ('menanyai');
INSERT INTO `stopword` VALUES ('menanyakan');
INSERT INTO `stopword` VALUES ('mendapat');
INSERT INTO `stopword` VALUES ('mendapatkan');
INSERT INTO `stopword` VALUES ('mendatang');
INSERT INTO `stopword` VALUES ('mendatangi');
INSERT INTO `stopword` VALUES ('mendatangkan');
INSERT INTO `stopword` VALUES ('menegaskan');
INSERT INTO `stopword` VALUES ('mengakhiri');
INSERT INTO `stopword` VALUES ('mengapa');
INSERT INTO `stopword` VALUES ('mengatakan');
INSERT INTO `stopword` VALUES ('mengatakannya');
INSERT INTO `stopword` VALUES ('mengenai');
INSERT INTO `stopword` VALUES ('mengerjakan');
INSERT INTO `stopword` VALUES ('mengetahui');
INSERT INTO `stopword` VALUES ('menggunakan');
INSERT INTO `stopword` VALUES ('menghendaki');
INSERT INTO `stopword` VALUES ('mengibaratkan');
INSERT INTO `stopword` VALUES ('mengibaratkannya');
INSERT INTO `stopword` VALUES ('mengingat');
INSERT INTO `stopword` VALUES ('mengingatkan');
INSERT INTO `stopword` VALUES ('menginginkan');
INSERT INTO `stopword` VALUES ('mengira');
INSERT INTO `stopword` VALUES ('mengucapkan');
INSERT INTO `stopword` VALUES ('mengucapkannya');
INSERT INTO `stopword` VALUES ('mengungkapkan');
INSERT INTO `stopword` VALUES ('menjadi');
INSERT INTO `stopword` VALUES ('menjawab');
INSERT INTO `stopword` VALUES ('menjelaskan');
INSERT INTO `stopword` VALUES ('menuju');
INSERT INTO `stopword` VALUES ('menunjuk');
INSERT INTO `stopword` VALUES ('menunjuki');
INSERT INTO `stopword` VALUES ('menunjukkan');
INSERT INTO `stopword` VALUES ('menunjuknya');
INSERT INTO `stopword` VALUES ('menurut');
INSERT INTO `stopword` VALUES ('menuturkan');
INSERT INTO `stopword` VALUES ('menyampaikan');
INSERT INTO `stopword` VALUES ('menyangkut');
INSERT INTO `stopword` VALUES ('menyatakan');
INSERT INTO `stopword` VALUES ('menyebutkan');
INSERT INTO `stopword` VALUES ('menyeluruh');
INSERT INTO `stopword` VALUES ('menyiapkan');
INSERT INTO `stopword` VALUES ('merasa');
INSERT INTO `stopword` VALUES ('mereka');
INSERT INTO `stopword` VALUES ('merekalah');
INSERT INTO `stopword` VALUES ('merupakan');
INSERT INTO `stopword` VALUES ('meski');
INSERT INTO `stopword` VALUES ('meskipun');
INSERT INTO `stopword` VALUES ('meyakini');
INSERT INTO `stopword` VALUES ('meyakinkan');
INSERT INTO `stopword` VALUES ('minta');
INSERT INTO `stopword` VALUES ('mirip');
INSERT INTO `stopword` VALUES ('misal');
INSERT INTO `stopword` VALUES ('misalkan');
INSERT INTO `stopword` VALUES ('misalnya');
INSERT INTO `stopword` VALUES ('mula');
INSERT INTO `stopword` VALUES ('mulai');
INSERT INTO `stopword` VALUES ('mulailah');
INSERT INTO `stopword` VALUES ('mulanya');
INSERT INTO `stopword` VALUES ('mungkin');
INSERT INTO `stopword` VALUES ('mungkinkah');
INSERT INTO `stopword` VALUES ('nah');
INSERT INTO `stopword` VALUES ('naik');
INSERT INTO `stopword` VALUES ('namun');
INSERT INTO `stopword` VALUES ('nanti');
INSERT INTO `stopword` VALUES ('nantinya');
INSERT INTO `stopword` VALUES ('nyaris');
INSERT INTO `stopword` VALUES ('nyatanya');
INSERT INTO `stopword` VALUES ('olah');
INSERT INTO `stopword` VALUES ('oleh');
INSERT INTO `stopword` VALUES ('olehnya');
INSERT INTO `stopword` VALUES ('pada');
INSERT INTO `stopword` VALUES ('padahal');
INSERT INTO `stopword` VALUES ('padanya');
INSERT INTO `stopword` VALUES ('pak');
INSERT INTO `stopword` VALUES ('paling');
INSERT INTO `stopword` VALUES ('panjang');
INSERT INTO `stopword` VALUES ('pantas');
INSERT INTO `stopword` VALUES ('para');
INSERT INTO `stopword` VALUES ('pasti');
INSERT INTO `stopword` VALUES ('pastilah');
INSERT INTO `stopword` VALUES ('penting');
INSERT INTO `stopword` VALUES ('pentingnya');
INSERT INTO `stopword` VALUES ('per');
INSERT INTO `stopword` VALUES ('percuma');
INSERT INTO `stopword` VALUES ('perlu');
INSERT INTO `stopword` VALUES ('perlukah');
INSERT INTO `stopword` VALUES ('perlunya');
INSERT INTO `stopword` VALUES ('pernah');
INSERT INTO `stopword` VALUES ('persoalan');
INSERT INTO `stopword` VALUES ('pertama');
INSERT INTO `stopword` VALUES ('pertanyaan');
INSERT INTO `stopword` VALUES ('pertanyakan');
INSERT INTO `stopword` VALUES ('pihak');
INSERT INTO `stopword` VALUES ('pihaknya');
INSERT INTO `stopword` VALUES ('pukul');
INSERT INTO `stopword` VALUES ('pula');
INSERT INTO `stopword` VALUES ('pun');
INSERT INTO `stopword` VALUES ('punya');
INSERT INTO `stopword` VALUES ('rasa');
INSERT INTO `stopword` VALUES ('rasanya');
INSERT INTO `stopword` VALUES ('rata');
INSERT INTO `stopword` VALUES ('rupanya');
INSERT INTO `stopword` VALUES ('saat');
INSERT INTO `stopword` VALUES ('saatnya');
INSERT INTO `stopword` VALUES ('saja');
INSERT INTO `stopword` VALUES ('sajalah');
INSERT INTO `stopword` VALUES ('saling');
INSERT INTO `stopword` VALUES ('sama');
INSERT INTO `stopword` VALUES ('sambil');
INSERT INTO `stopword` VALUES ('sampai');
INSERT INTO `stopword` VALUES ('sampaikan');
INSERT INTO `stopword` VALUES ('sana');
INSERT INTO `stopword` VALUES ('sangat');
INSERT INTO `stopword` VALUES ('sangatlah');
INSERT INTO `stopword` VALUES ('satu');
INSERT INTO `stopword` VALUES ('saya');
INSERT INTO `stopword` VALUES ('sayalah');
INSERT INTO `stopword` VALUES ('se');
INSERT INTO `stopword` VALUES ('sebab');
INSERT INTO `stopword` VALUES ('sebabnya');
INSERT INTO `stopword` VALUES ('sebagai');
INSERT INTO `stopword` VALUES ('sebagaimana');
INSERT INTO `stopword` VALUES ('sebagainya');
INSERT INTO `stopword` VALUES ('sebagian');
INSERT INTO `stopword` VALUES ('sebaik');
INSERT INTO `stopword` VALUES ('sebaiknya');
INSERT INTO `stopword` VALUES ('sebaliknya');
INSERT INTO `stopword` VALUES ('sebanyak');
INSERT INTO `stopword` VALUES ('sebegini');
INSERT INTO `stopword` VALUES ('sebegitu');
INSERT INTO `stopword` VALUES ('sebelum');
INSERT INTO `stopword` VALUES ('sebelumnya');
INSERT INTO `stopword` VALUES ('sebenarnya');
INSERT INTO `stopword` VALUES ('seberapa');
INSERT INTO `stopword` VALUES ('sebesar');
INSERT INTO `stopword` VALUES ('sebetulnya');
INSERT INTO `stopword` VALUES ('sebisanya');
INSERT INTO `stopword` VALUES ('sebuah');
INSERT INTO `stopword` VALUES ('sebut');
INSERT INTO `stopword` VALUES ('sebutlah');
INSERT INTO `stopword` VALUES ('sebutnya');
INSERT INTO `stopword` VALUES ('secara');
INSERT INTO `stopword` VALUES ('secukupnya');
INSERT INTO `stopword` VALUES ('sedang');
INSERT INTO `stopword` VALUES ('sedangkan');
INSERT INTO `stopword` VALUES ('sedemikian');
INSERT INTO `stopword` VALUES ('sedikit');
INSERT INTO `stopword` VALUES ('sedikitnya');
INSERT INTO `stopword` VALUES ('seenaknya');
INSERT INTO `stopword` VALUES ('segala');
INSERT INTO `stopword` VALUES ('segalanya');
INSERT INTO `stopword` VALUES ('segera');
INSERT INTO `stopword` VALUES ('seharusnya');
INSERT INTO `stopword` VALUES ('sehingga');
INSERT INTO `stopword` VALUES ('seingat');
INSERT INTO `stopword` VALUES ('sejak');
INSERT INTO `stopword` VALUES ('sejauh');
INSERT INTO `stopword` VALUES ('sejenak');
INSERT INTO `stopword` VALUES ('sejumlah');
INSERT INTO `stopword` VALUES ('sekadar');
INSERT INTO `stopword` VALUES ('sekadarnya');
INSERT INTO `stopword` VALUES ('sekali');
INSERT INTO `stopword` VALUES ('sekalian');
INSERT INTO `stopword` VALUES ('sekaligus');
INSERT INTO `stopword` VALUES ('sekalipun');
INSERT INTO `stopword` VALUES ('sekarang');
INSERT INTO `stopword` VALUES ('sekecil');
INSERT INTO `stopword` VALUES ('seketika');
INSERT INTO `stopword` VALUES ('sekiranya');
INSERT INTO `stopword` VALUES ('sekitar');
INSERT INTO `stopword` VALUES ('sekitarnya');
INSERT INTO `stopword` VALUES ('sekurang');
INSERT INTO `stopword` VALUES ('sekurangnya');
INSERT INTO `stopword` VALUES ('sela');
INSERT INTO `stopword` VALUES ('selain');
INSERT INTO `stopword` VALUES ('selaku');
INSERT INTO `stopword` VALUES ('selalu');
INSERT INTO `stopword` VALUES ('selama');
INSERT INTO `stopword` VALUES ('selamanya');
INSERT INTO `stopword` VALUES ('selanjutnya');
INSERT INTO `stopword` VALUES ('seluruh');
INSERT INTO `stopword` VALUES ('seluruhnya');
INSERT INTO `stopword` VALUES ('semacam');
INSERT INTO `stopword` VALUES ('semakin');
INSERT INTO `stopword` VALUES ('semampu');
INSERT INTO `stopword` VALUES ('semampunya');
INSERT INTO `stopword` VALUES ('semasa');
INSERT INTO `stopword` VALUES ('semasih');
INSERT INTO `stopword` VALUES ('semata');
INSERT INTO `stopword` VALUES ('semaunya');
INSERT INTO `stopword` VALUES ('sementara');
INSERT INTO `stopword` VALUES ('semisal');
INSERT INTO `stopword` VALUES ('semisalnya');
INSERT INTO `stopword` VALUES ('sempat');
INSERT INTO `stopword` VALUES ('semua');
INSERT INTO `stopword` VALUES ('semuanya');
INSERT INTO `stopword` VALUES ('semula');
INSERT INTO `stopword` VALUES ('sendiri');
INSERT INTO `stopword` VALUES ('sendirian');
INSERT INTO `stopword` VALUES ('sendirinya');
INSERT INTO `stopword` VALUES ('seolah');
INSERT INTO `stopword` VALUES ('seorang');
INSERT INTO `stopword` VALUES ('sepanjang');
INSERT INTO `stopword` VALUES ('sepantasnya');
INSERT INTO `stopword` VALUES ('sepantasnyalah');
INSERT INTO `stopword` VALUES ('seperlunya');
INSERT INTO `stopword` VALUES ('seperti');
INSERT INTO `stopword` VALUES ('sepertinya');
INSERT INTO `stopword` VALUES ('sepihak');
INSERT INTO `stopword` VALUES ('sering');
INSERT INTO `stopword` VALUES ('seringnya');
INSERT INTO `stopword` VALUES ('serta');
INSERT INTO `stopword` VALUES ('serupa');
INSERT INTO `stopword` VALUES ('sesaat');
INSERT INTO `stopword` VALUES ('sesama');
INSERT INTO `stopword` VALUES ('sesampai');
INSERT INTO `stopword` VALUES ('sesegera');
INSERT INTO `stopword` VALUES ('sesekali');
INSERT INTO `stopword` VALUES ('seseorang');
INSERT INTO `stopword` VALUES ('sesuatu');
INSERT INTO `stopword` VALUES ('sesuatunya');
INSERT INTO `stopword` VALUES ('sesudah');
INSERT INTO `stopword` VALUES ('sesudahnya');
INSERT INTO `stopword` VALUES ('setelah');
INSERT INTO `stopword` VALUES ('setempat');
INSERT INTO `stopword` VALUES ('setengah');
INSERT INTO `stopword` VALUES ('seterusnya');
INSERT INTO `stopword` VALUES ('setiap');
INSERT INTO `stopword` VALUES ('setiba');
INSERT INTO `stopword` VALUES ('setibanya');
INSERT INTO `stopword` VALUES ('setidak');
INSERT INTO `stopword` VALUES ('setidaknya');
INSERT INTO `stopword` VALUES ('setinggi');
INSERT INTO `stopword` VALUES ('seusai');
INSERT INTO `stopword` VALUES ('sewaktu');
INSERT INTO `stopword` VALUES ('siap');
INSERT INTO `stopword` VALUES ('siapa');
INSERT INTO `stopword` VALUES ('siapakah');
INSERT INTO `stopword` VALUES ('siapapun');
INSERT INTO `stopword` VALUES ('sini');
INSERT INTO `stopword` VALUES ('sinilah');
INSERT INTO `stopword` VALUES ('soal');
INSERT INTO `stopword` VALUES ('soalnya');
INSERT INTO `stopword` VALUES ('suatu');
INSERT INTO `stopword` VALUES ('sudah');
INSERT INTO `stopword` VALUES ('sudahkah');
INSERT INTO `stopword` VALUES ('sudahlah');
INSERT INTO `stopword` VALUES ('supaya');
INSERT INTO `stopword` VALUES ('tadi');
INSERT INTO `stopword` VALUES ('tadinya');
INSERT INTO `stopword` VALUES ('tahu');
INSERT INTO `stopword` VALUES ('tahun');
INSERT INTO `stopword` VALUES ('tak');
INSERT INTO `stopword` VALUES ('tama');
INSERT INTO `stopword` VALUES ('tambah');
INSERT INTO `stopword` VALUES ('tambahnya');
INSERT INTO `stopword` VALUES ('tampak');
INSERT INTO `stopword` VALUES ('tampaknya');
INSERT INTO `stopword` VALUES ('tandas');
INSERT INTO `stopword` VALUES ('tandasnya');
INSERT INTO `stopword` VALUES ('tanpa');
INSERT INTO `stopword` VALUES ('tanya');
INSERT INTO `stopword` VALUES ('tanyakan');
INSERT INTO `stopword` VALUES ('tanyanya');
INSERT INTO `stopword` VALUES ('tapi');
INSERT INTO `stopword` VALUES ('tegas');
INSERT INTO `stopword` VALUES ('tegasnya');
INSERT INTO `stopword` VALUES ('telah');
INSERT INTO `stopword` VALUES ('tempat');
INSERT INTO `stopword` VALUES ('tengah');
INSERT INTO `stopword` VALUES ('tentang');
INSERT INTO `stopword` VALUES ('tentu');
INSERT INTO `stopword` VALUES ('tentulah');
INSERT INTO `stopword` VALUES ('tentunya');
INSERT INTO `stopword` VALUES ('tepat');
INSERT INTO `stopword` VALUES ('terakhir');
INSERT INTO `stopword` VALUES ('terasa');
INSERT INTO `stopword` VALUES ('terbanyak');
INSERT INTO `stopword` VALUES ('terdahulu');
INSERT INTO `stopword` VALUES ('terdapat');
INSERT INTO `stopword` VALUES ('terdiri');
INSERT INTO `stopword` VALUES ('terhadap');
INSERT INTO `stopword` VALUES ('terhadapnya');
INSERT INTO `stopword` VALUES ('teringat');
INSERT INTO `stopword` VALUES ('terjadi');
INSERT INTO `stopword` VALUES ('terjadilah');
INSERT INTO `stopword` VALUES ('terjadinya');
INSERT INTO `stopword` VALUES ('terkira');
INSERT INTO `stopword` VALUES ('terlalu');
INSERT INTO `stopword` VALUES ('terlebih');
INSERT INTO `stopword` VALUES ('terlihat');
INSERT INTO `stopword` VALUES ('termasuk');
INSERT INTO `stopword` VALUES ('ternyata');
INSERT INTO `stopword` VALUES ('tersampaikan');
INSERT INTO `stopword` VALUES ('tersebut');
INSERT INTO `stopword` VALUES ('tersebutlah');
INSERT INTO `stopword` VALUES ('tertentu');
INSERT INTO `stopword` VALUES ('tertuju');
INSERT INTO `stopword` VALUES ('terus');
INSERT INTO `stopword` VALUES ('terutama');
INSERT INTO `stopword` VALUES ('tetap');
INSERT INTO `stopword` VALUES ('tetapi');
INSERT INTO `stopword` VALUES ('tiap');
INSERT INTO `stopword` VALUES ('tiba');
INSERT INTO `stopword` VALUES ('tidak');
INSERT INTO `stopword` VALUES ('tidakkah');
INSERT INTO `stopword` VALUES ('tidaklah');
INSERT INTO `stopword` VALUES ('tidaknya');
INSERT INTO `stopword` VALUES ('tiga');
INSERT INTO `stopword` VALUES ('tinggi');
INSERT INTO `stopword` VALUES ('toh');
INSERT INTO `stopword` VALUES ('tunjuk');
INSERT INTO `stopword` VALUES ('turut');
INSERT INTO `stopword` VALUES ('tutur');
INSERT INTO `stopword` VALUES ('tuturnya');
INSERT INTO `stopword` VALUES ('ucap');
INSERT INTO `stopword` VALUES ('ucapnya');
INSERT INTO `stopword` VALUES ('ujar');
INSERT INTO `stopword` VALUES ('ujarnya');
INSERT INTO `stopword` VALUES ('umum');
INSERT INTO `stopword` VALUES ('umumnya');
INSERT INTO `stopword` VALUES ('ungkap');
INSERT INTO `stopword` VALUES ('ungkapnya');
INSERT INTO `stopword` VALUES ('untuk');
INSERT INTO `stopword` VALUES ('usah');
INSERT INTO `stopword` VALUES ('usai');
INSERT INTO `stopword` VALUES ('waduh');
INSERT INTO `stopword` VALUES ('wah');
INSERT INTO `stopword` VALUES ('wahai');
INSERT INTO `stopword` VALUES ('waktu');
INSERT INTO `stopword` VALUES ('waktunya');
INSERT INTO `stopword` VALUES ('walau');
INSERT INTO `stopword` VALUES ('walaupun');
INSERT INTO `stopword` VALUES ('wong');
INSERT INTO `stopword` VALUES ('yaitu');
INSERT INTO `stopword` VALUES ('yakin');
INSERT INTO `stopword` VALUES ('yakni');
INSERT INTO `stopword` VALUES ('yang');

-- ----------------------------
-- Table structure for tfidf
-- ----------------------------
DROP TABLE IF EXISTS `tfidf`;
CREATE TABLE `tfidf`  (
  `id` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `no` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `kata` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `freq` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tfidf
-- ----------------------------
INSERT INTO `tfidf` VALUES ('1', '1', 'this', '1');
INSERT INTO `tfidf` VALUES ('1', '2', 'is', '1');
INSERT INTO `tfidf` VALUES ('1', '3', 'a', '2');
INSERT INTO `tfidf` VALUES ('1', '4', 'sample', '1');
INSERT INTO `tfidf` VALUES ('2', '1', 'this', '1');
INSERT INTO `tfidf` VALUES ('2', '2', 'is', '1');
INSERT INTO `tfidf` VALUES ('2', '3', 'another', '2');
INSERT INTO `tfidf` VALUES ('2', '4', 'example', '3');

-- ----------------------------
-- Table structure for token
-- ----------------------------
DROP TABLE IF EXISTS `token`;
CREATE TABLE `token`  (
  `id` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `no` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `kode` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `kata` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `freq` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  INDEX `no`(`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of token
-- ----------------------------
INSERT INTO `token` VALUES ('1', '1', '0', 'covid', '1');
INSERT INTO `token` VALUES ('1', '3', '0', 'sakit', '1');
INSERT INTO `token` VALUES ('1', '4', '0', 'tular', '1');
INSERT INTO `token` VALUES ('1', '6', '0', 'sebab', '1');
INSERT INTO `token` VALUES ('1', '8', '0', 'jenis', '1');
INSERT INTO `token` VALUES ('1', '9', '0', 'virus', '1');
INSERT INTO `token` VALUES ('1', '10', '0', 'corona', '1');
INSERT INTO `token` VALUES ('1', '13', '0', 'temu', '1');
INSERT INTO `token` VALUES ('1', '14', '0', 'virus', '1');
INSERT INTO `token` VALUES ('1', '17', '0', 'virus', '1');
INSERT INTO `token` VALUES ('1', '20', '0', 'sakit', '1');
INSERT INTO `token` VALUES ('1', '23', '0', 'kenal', '1');
INSERT INTO `token` VALUES ('1', '26', '0', 'wabah', '1');
INSERT INTO `token` VALUES ('1', '28', '0', 'wuhan', '1');
INSERT INTO `token` VALUES ('1', '29', '0', 'cina', '1');
INSERT INTO `token` VALUES ('1', '32', '0', 'desember', '1');
INSERT INTO `token` VALUES ('2', '2', '0', 'tes', '1');
INSERT INTO `token` VALUES ('2', '3', '0', 'antibodi', '1');
INSERT INTO `token` VALUES ('2', '5', '0', 'pcr', '1');
INSERT INTO `token` VALUES ('2', '6', '0', 'milik', '1');
INSERT INTO `token` VALUES ('2', '7', '0', 'jendela', '1');
INSERT INTO `token` VALUES ('2', '10', '0', 'optimum', '1');
INSERT INTO `token` VALUES ('2', '13', '0', 'inkubasi', '1');
INSERT INTO `token` VALUES ('2', '15', '0', 'infeksi', '1');
INSERT INTO `token` VALUES ('2', '17', '0', 'hasil', '1');
INSERT INTO `token` VALUES ('2', '18', '0', 'tes', '1');
INSERT INTO `token` VALUES ('2', '23', '0', 'kuat', '1');
INSERT INTO `token` VALUES ('2', '25', '0', 'periksa', '1');
INSERT INTO `token` VALUES ('2', '26', '0', 'gejala', '1');
INSERT INTO `token` VALUES ('2', '27', '0', 'gejala', '1');
INSERT INTO `token` VALUES ('2', '28', '0', 'klinis', '1');
INSERT INTO `token` VALUES ('2', '30', '0', 'sejarah', '1');
INSERT INTO `token` VALUES ('2', '31', '0', 'jalan', '1');
INSERT INTO `token` VALUES ('2', '32', '0', 'kontak', '1');
INSERT INTO `token` VALUES ('2', '34', '0', 'odp', '1');
INSERT INTO `token` VALUES ('2', '35', '0', 'pdp', '1');
INSERT INTO `token` VALUES ('2', '36', '0', 'positif', '1');
INSERT INTO `token` VALUES ('2', '37', '0', 'covid', '1');
INSERT INTO `token` VALUES ('2', '39', '0', 'hasil', '1');
INSERT INTO `token` VALUES ('2', '40', '0', 'tes', '1');
INSERT INTO `token` VALUES ('2', '41', '0', 'negatif', '1');
INSERT INTO `token` VALUES ('2', '46', '0', 'gejala', '1');
INSERT INTO `token` VALUES ('2', '47', '0', 'klinis', '1');
INSERT INTO `token` VALUES ('2', '48', '0', 'covid', '1');
INSERT INTO `token` VALUES ('2', '51', '0', 'sejarah', '1');
INSERT INTO `token` VALUES ('2', '52', '0', 'kontak', '1');
INSERT INTO `token` VALUES ('2', '54', '0', 'pasien', '1');
INSERT INTO `token` VALUES ('2', '55', '0', 'positif', '1');
INSERT INTO `token` VALUES ('2', '56', '0', 'covid', '1');
INSERT INTO `token` VALUES ('2', '59', '0', 'bebas', '1');
INSERT INTO `token` VALUES ('2', '62', '0', 'protokol', '1');
INSERT INTO `token` VALUES ('2', '63', '0', 'covid', '1');
INSERT INTO `token` VALUES ('3', '1', '0', 'duduk', '1');
INSERT INTO `token` VALUES ('3', '2', '0', 'pancasila', '1');
INSERT INTO `token` VALUES ('3', '4', '0', 'dasar', '1');
INSERT INTO `token` VALUES ('3', '5', '0', 'negara', '1');
INSERT INTO `token` VALUES ('3', '7', '0', 'pandang', '1');
INSERT INTO `token` VALUES ('3', '8', '0', 'hidup', '1');
INSERT INTO `token` VALUES ('3', '9', '0', 'bangsa', '1');
INSERT INTO `token` VALUES ('3', '11', '0', 'pakat', '1');
INSERT INTO `token` VALUES ('3', '14', '0', 'bangsa', '1');
INSERT INTO `token` VALUES ('3', '15', '0', 'indonesia', '1');
INSERT INTO `token` VALUES ('3', '16', '0', 'notonagoro', '1');
INSERT INTO `token` VALUES ('3', '18', '0', 'tim', '1');
INSERT INTO `token` VALUES ('3', '19', '0', 'mpr', '1');
INSERT INTO `token` VALUES ('3', '20', '0', 'ri', '1');
INSERT INTO `token` VALUES ('3', '23', '0', 'unsur', '1');
INSERT INTO `token` VALUES ('3', '27', '0', 'pancasila', '1');
INSERT INTO `token` VALUES ('3', '33', '0', 'bentuk', '1');
INSERT INTO `token` VALUES ('3', '34', '0', 'negara', '1');
INSERT INTO `token` VALUES ('3', '35', '0', 'indonesia', '1');
INSERT INTO `token` VALUES ('3', '42', '0', 'milik', '1');
INSERT INTO `token` VALUES ('3', '44', '0', 'rakyat', '1');
INSERT INTO `token` VALUES ('3', '45', '0', 'bangsa', '1');
INSERT INTO `token` VALUES ('3', '46', '0', 'indonesia', '1');
INSERT INTO `token` VALUES ('3', '48', '0', 'nyata', '1');
INSERT INTO `token` VALUES ('3', '51', '0', 'hidup', '1');
INSERT INTO `token` VALUES ('3', '53', '0', 'jiwa', '1');
INSERT INTO `token` VALUES ('3', '54', '0', 'masyarakat', '1');
INSERT INTO `token` VALUES ('4', '1', '0', 'sektor', '1');
INSERT INTO `token` VALUES ('4', '2', '0', 'didik', '1');
INSERT INTO `token` VALUES ('4', '4', '0', 'strategis', '1');
INSERT INTO `token` VALUES ('4', '6', '0', 'penting', '1');
INSERT INTO `token` VALUES ('4', '7', '0', 'nasional', '1');
INSERT INTO `token` VALUES ('4', '9', '0', 'sentuh', '1');
INSERT INTO `token` VALUES ('4', '10', '0', 'juta', '1');
INSERT INTO `token` VALUES ('4', '11', '0', 'siswa', '1');
INSERT INTO `token` VALUES ('4', '15', '0', 'produk', '1');
INSERT INTO `token` VALUES ('4', '16', '0', 'produk', '1');
INSERT INTO `token` VALUES ('4', '17', '0', 'jasa', '1');
INSERT INTO `token` VALUES ('4', '18', '0', 'teknologi', '1');
INSERT INTO `token` VALUES ('4', '19', '0', 'edukasi', '1');
INSERT INTO `token` VALUES ('4', '20', '0', 'swasta', '1');
INSERT INTO `token` VALUES ('4', '22', '0', 'wajib', '1');
INSERT INTO `token` VALUES ('4', '23', '0', 'milik', '1');
INSERT INTO `token` VALUES ('4', '24', '0', 'tingkat', '1');
INSERT INTO `token` VALUES ('4', '25', '0', 'komponen', '1');
INSERT INTO `token` VALUES ('4', '27', '0', 'negeri', '1');
INSERT INTO `token` VALUES ('4', '28', '0', 'tkdn', '1');
INSERT INTO `token` VALUES ('4', '30', '0', 'maksimal', '1');
INSERT INTO `token` VALUES ('4', '32', '0', 'penuh', '1');
INSERT INTO `token` VALUES ('4', '33', '0', 'atur', '1');
INSERT INTO `token` VALUES ('4', '36', '0', 'dana', '1');
INSERT INTO `token` VALUES ('4', '37', '0', 'masyarakat', '1');
INSERT INTO `token` VALUES ('4', '39', '0', 'kabur', '1');
INSERT INTO `token` VALUES ('4', '41', '0', 'usaha', '1');
INSERT INTO `token` VALUES ('4', '43', '0', 'negeri', '1');
INSERT INTO `token` VALUES ('4', '45', '0', 'tekan', '1');
INSERT INTO `token` VALUES ('4', '46', '0', 'rupiah', '1');
INSERT INTO `token` VALUES ('5', '1', '0', 'manfaat', '1');
INSERT INTO `token` VALUES ('5', '2', '0', 'minum', '1');
INSERT INTO `token` VALUES ('5', '3', '0', 'air', '1');
INSERT INTO `token` VALUES ('5', '4', '0', 'putih', '1');
INSERT INTO `token` VALUES ('5', '6', '0', 'perut', '1');
INSERT INTO `token` VALUES ('5', '7', '0', 'kosong', '1');
INSERT INTO `token` VALUES ('5', '10', '0', 'pagi', '1');
INSERT INTO `token` VALUES ('5', '13', '0', 'sehat', '1');
INSERT INTO `token` VALUES ('5', '14', '0', 'tubuh', '1');
INSERT INTO `token` VALUES ('5', '18', '0', 'terap', '1');
INSERT INTO `token` VALUES ('5', '19', '0', 'biasa', '1');
INSERT INTO `token` VALUES ('5', '20', '0', 'sehat', '1');
INSERT INTO `token` VALUES ('5', '22', '0', 'sederhana', '1');
INSERT INTO `token` VALUES ('5', '25', '0', 'hari', '1');
INSERT INTO `token` VALUES ('5', '28', '0', 'perut', '1');
INSERT INTO `token` VALUES ('5', '30', '0', 'kosong', '1');
INSERT INTO `token` VALUES ('5', '32', '0', 'pagi', '1');
INSERT INTO `token` VALUES ('5', '36', '0', 'hati', '1');
INSERT INTO `token` VALUES ('5', '37', '0', 'hati', '1');
INSERT INTO `token` VALUES ('5', '39', '0', 'konsumsi', '1');
INSERT INTO `token` VALUES ('5', '40', '0', 'makan', '1');
INSERT INTO `token` VALUES ('5', '43', '0', 'masuk', '1');
INSERT INTO `token` VALUES ('5', '46', '0', 'tubuh', '1');
INSERT INTO `token` VALUES ('6', '1', '0', 'perintah', '1');
INSERT INTO `token` VALUES ('6', '2', '0', 'anggar', '1');
INSERT INTO `token` VALUES ('6', '3', '0', 'rp', '1');
INSERT INTO `token` VALUES ('6', '4', '0', 'triliun', '1');
INSERT INTO `token` VALUES ('6', '6', '0', 'dana', '1');
INSERT INTO `token` VALUES ('6', '7', '0', 'dana', '1');
INSERT INTO `token` VALUES ('6', '8', '0', 'tangan', '1');
INSERT INTO `token` VALUES ('6', '9', '0', 'covid', '1');
INSERT INTO `token` VALUES ('6', '11', '0', 'dana', '1');
INSERT INTO `token` VALUES ('6', '13', '0', 'sektor', '1');
INSERT INTO `token` VALUES ('6', '14', '0', 'sehat', '1');
INSERT INTO `token` VALUES ('6', '16', '0', 'jatah', '1');
INSERT INTO `token` VALUES ('6', '17', '0', 'rp', '1');
INSERT INTO `token` VALUES ('6', '18', '0', 'triliun', '1');
INSERT INTO `token` VALUES ('6', '20', '0', 'lapor', '1');
INSERT INTO `token` VALUES ('6', '22', '0', 'anggar', '1');
INSERT INTO `token` VALUES ('6', '24', '0', 'sektor', '1');
INSERT INTO `token` VALUES ('6', '25', '0', 'sehat', '1');
INSERT INTO `token` VALUES ('6', '27', '0', 'serap', '1');
INSERT INTO `token` VALUES ('7', '1', '0', 'tips', '1');
INSERT INTO `token` VALUES ('7', '2', '0', 'mudah', '1');
INSERT INTO `token` VALUES ('7', '3', '0', 'manajemen', '1');
INSERT INTO `token` VALUES ('7', '4', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('7', '7', '0', 'rumah', '1');
INSERT INTO `token` VALUES ('8', '1', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('8', '2', '0', 'plastik', '1');
INSERT INTO `token` VALUES ('8', '4', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('8', '9', '0', 'masyarakat', '1');
INSERT INTO `token` VALUES ('8', '11', '0', 'tiap', '1');
INSERT INTO `token` VALUES ('8', '12', '0', 'giat', '1');
INSERT INTO `token` VALUES ('8', '14', '0', 'libat', '1');
INSERT INTO `token` VALUES ('8', '15', '0', 'guna', '1');
INSERT INTO `token` VALUES ('8', '16', '0', 'plastik', '1');
INSERT INTO `token` VALUES ('8', '19', '0', 'beli', '1');
INSERT INTO `token` VALUES ('8', '20', '0', 'minum', '1');
INSERT INTO `token` VALUES ('8', '22', '0', 'makannan', '1');
INSERT INTO `token` VALUES ('8', '24', '0', 'kemas', '1');
INSERT INTO `token` VALUES ('8', '28', '0', 'plastik', '1');
INSERT INTO `token` VALUES ('8', '30', '0', 'bawa', '1');
INSERT INTO `token` VALUES ('8', '34', '0', 'kantong', '1');
INSERT INTO `token` VALUES ('8', '35', '0', 'kresek', '1');
INSERT INTO `token` VALUES ('8', '37', '0', 'buat', '1');
INSERT INTO `token` VALUES ('8', '39', '0', 'plastik', '1');
INSERT INTO `token` VALUES ('8', '45', '0', 'contoh', '1');
INSERT INTO `token` VALUES ('8', '46', '0', 'hari', '1');
INSERT INTO `token` VALUES ('8', '48', '0', 'guna', '1');
INSERT INTO `token` VALUES ('8', '49', '0', 'plastik', '1');
INSERT INTO `token` VALUES ('8', '51', '0', 'hidup', '1');
INSERT INTO `token` VALUES ('8', '52', '0', 'manusia', '1');
INSERT INTO `token` VALUES ('8', '53', '0', 'biasa', '1');
INSERT INTO `token` VALUES ('8', '55', '0', 'timbul', '1');
INSERT INTO `token` VALUES ('8', '56', '0', 'tinggi', '1');
INSERT INTO `token` VALUES ('8', '57', '0', 'angka', '1');
INSERT INTO `token` VALUES ('8', '58', '0', 'plastik', '1');
INSERT INTO `token` VALUES ('8', '60', '0', 'plastik', '1');
INSERT INTO `token` VALUES ('8', '63', '0', 'sifat', '1');
INSERT INTO `token` VALUES ('8', '65', '0', 'pakai', '1');
INSERT INTO `token` VALUES ('8', '67', '0', 'buang', '1');
INSERT INTO `token` VALUES ('9', '1', '0', 'habis', '1');
INSERT INTO `token` VALUES ('9', '4', '0', 'sahabat', '1');
INSERT INTO `token` VALUES ('9', '6', '0', 'keluarga', '1');
INSERT INTO `token` VALUES ('9', '8', '0', 'wisata', '1');
INSERT INTO `token` VALUES ('9', '10', '0', 'pantai', '1');
INSERT INTO `token` VALUES ('9', '12', '0', 'laut', '1');
INSERT INTO `token` VALUES ('9', '16', '0', 'senang', '1');
INSERT INTO `token` VALUES ('9', '24', '0', 'perhati', '1');
INSERT INTO `token` VALUES ('9', '27', '0', 'buang', '1');
INSERT INTO `token` VALUES ('9', '28', '0', 'sembarang', '1');
INSERT INTO `token` VALUES ('9', '30', '0', 'tinggal', '1');
INSERT INTO `token` VALUES ('9', '31', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('9', '33', '0', 'kawasan', '1');
INSERT INTO `token` VALUES ('9', '34', '0', 'pantai', '1');
INSERT INTO `token` VALUES ('9', '36', '0', 'laut', '1');
INSERT INTO `token` VALUES ('9', '37', '0', 'pasti', '1');
INSERT INTO `token` VALUES ('9', '40', '0', 'buang', '1');
INSERT INTO `token` VALUES ('9', '41', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('9', '43', '0', 'tempat', '1');
INSERT INTO `token` VALUES ('9', '45', '0', 'pergi', '1');
INSERT INTO `token` VALUES ('9', '47', '0', 'lokasi', '1');
INSERT INTO `token` VALUES ('9', '48', '0', 'wisata', '1');
INSERT INTO `token` VALUES ('10', '1', '0', 'tanggulang', '1');
INSERT INTO `token` VALUES ('10', '2', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('10', '3', '0', 'plastik', '1');
INSERT INTO `token` VALUES ('10', '5', '0', 'laut', '1');
INSERT INTO `token` VALUES ('10', '6', '0', 'indonesia', '1');
INSERT INTO `token` VALUES ('10', '7', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('10', '8', '0', 'plastik', '1');
INSERT INTO `token` VALUES ('10', '12', '0', 'laut', '1');
INSERT INTO `token` VALUES ('10', '13', '0', 'indonesia', '1');
INSERT INTO `token` VALUES ('10', '15', '0', 'tingkat', '1');
INSERT INTO `token` VALUES ('10', '19', '0', 'buang', '1');
INSERT INTO `token` VALUES ('10', '20', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('10', '22', '0', 'sungai', '1');
INSERT INTO `token` VALUES ('10', '24', '0', 'tingkat', '1');
INSERT INTO `token` VALUES ('10', '25', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('10', '27', '0', 'buang', '1');
INSERT INTO `token` VALUES ('10', '29', '0', 'sungai', '1');
INSERT INTO `token` VALUES ('10', '35', '0', 'laut', '1');
INSERT INTO `token` VALUES ('10', '37', '0', 'laut', '1');
INSERT INTO `token` VALUES ('10', '41', '0', 'kotor', '1');
INSERT INTO `token` VALUES ('10', '42', '0', 'penuh', '1');
INSERT INTO `token` VALUES ('10', '44', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('10', '48', '0', 'perintah', '1');
INSERT INTO `token` VALUES ('10', '49', '0', 'indonesia', '1');
INSERT INTO `token` VALUES ('10', '52', '0', 'tanggulang', '1');
INSERT INTO `token` VALUES ('10', '54', '0', 'efektif', '1');
INSERT INTO `token` VALUES ('10', '56', '0', 'efisien', '1');
INSERT INTO `token` VALUES ('10', '61', '0', 'coba', '1');
INSERT INTO `token` VALUES ('10', '65', '0', 'volume', '1');
INSERT INTO `token` VALUES ('10', '66', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('10', '68', '0', 'laut', '1');
INSERT INTO `token` VALUES ('10', '69', '0', 'indonesia', '1');
INSERT INTO `token` VALUES ('10', '71', '0', 'tingkat', '1');
INSERT INTO `token` VALUES ('11', '1', '0', 'teknologi', '1');
INSERT INTO `token` VALUES ('11', '2', '0', 'olah', '1');
INSERT INTO `token` VALUES ('11', '3', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('11', '5', '0', 'pengaruh', '1');
INSERT INTO `token` VALUES ('11', '7', '0', 'nyaman', '1');
INSERT INTO `token` VALUES ('11', '9', '0', 'sehat', '1');
INSERT INTO `token` VALUES ('11', '10', '0', 'manusia', '1');
INSERT INTO `token` VALUES ('11', '13', '0', 'daerah', '1');
INSERT INTO `token` VALUES ('11', '16', '0', 'terap', '1');
INSERT INTO `token` VALUES ('11', '17', '0', 'teknologi', '1');
INSERT INTO `token` VALUES ('11', '18', '0', 'olah', '1');
INSERT INTO `token` VALUES ('11', '19', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('11', '30', '0', 'tahu', '1');
INSERT INTO `token` VALUES ('11', '33', '0', 'rasa', '1');
INSERT INTO `token` VALUES ('11', '34', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('11', '36', '0', 'buang', '1');
INSERT INTO `token` VALUES ('11', '41', '0', 'cari', '1');
INSERT INTO `token` VALUES ('11', '42', '0', 'lingkung', '1');
INSERT INTO `token` VALUES ('11', '43', '0', 'hidup', '1');
INSERT INTO `token` VALUES ('11', '44', '0', 'timbuk', '1');
INSERT INTO `token` VALUES ('11', '45', '0', 'efek', '1');
INSERT INTO `token` VALUES ('11', '47', '0', 'nyaman', '1');
INSERT INTO `token` VALUES ('11', '49', '0', 'efek', '1');
INSERT INTO `token` VALUES ('11', '50', '0', 'serius', '1');
INSERT INTO `token` VALUES ('11', '53', '0', 'ditumbulkan', '1');
INSERT INTO `token` VALUES ('11', '55', '0', 'datang', '1');
INSERT INTO `token` VALUES ('11', '56', '0', 'pencakit', '1');
INSERT INTO `token` VALUES ('11', '58', '0', 'racun', '1');
INSERT INTO `token` VALUES ('11', '62', '0', 'butuh', '1');
INSERT INTO `token` VALUES ('11', '64', '0', 'terap', '1');
INSERT INTO `token` VALUES ('11', '66', '0', 'guna', '1');
INSERT INTO `token` VALUES ('11', '67', '0', 'teknologi', '1');
INSERT INTO `token` VALUES ('11', '68', '0', 'olah', '1');
INSERT INTO `token` VALUES ('11', '69', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('12', '1', '0', 'buat', '1');
INSERT INTO `token` VALUES ('12', '2', '0', 'pupuk', '1');
INSERT INTO `token` VALUES ('12', '3', '0', 'kompos', '1');
INSERT INTO `token` VALUES ('12', '5', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('12', '6', '0', 'bekas', '1');
INSERT INTO `token` VALUES ('12', '8', '0', 'rumah', '1');
INSERT INTO `token` VALUES ('12', '9', '0', 'tangga', '1');
INSERT INTO `token` VALUES ('12', '11', '0', 'hasil', '1');
INSERT INTO `token` VALUES ('12', '12', '0', 'limbah', '1');
INSERT INTO `token` VALUES ('12', '15', '0', 'limbah', '1');
INSERT INTO `token` VALUES ('12', '16', '0', 'organik', '1');
INSERT INTO `token` VALUES ('12', '18', '0', 'limbah', '1');
INSERT INTO `token` VALUES ('12', '19', '0', 'anorganik', '1');
INSERT INTO `token` VALUES ('12', '22', '0', 'bentuk', '1');
INSERT INTO `token` VALUES ('12', '23', '0', 'limbah', '1');
INSERT INTO `token` VALUES ('12', '25', '0', 'hasil', '1');
INSERT INTO `token` VALUES ('12', '29', '0', 'cair', '1');
INSERT INTO `token` VALUES ('12', '32', '0', 'padat', '1');
INSERT INTO `token` VALUES ('12', '34', '0', 'limbah', '1');
INSERT INTO `token` VALUES ('12', '37', '0', 'olah', '1');
INSERT INTO `token` VALUES ('12', '41', '0', 'cari', '1');
INSERT INTO `token` VALUES ('12', '42', '0', 'lingkung', '1');
INSERT INTO `token` VALUES ('12', '45', '0', 'olah', '1');
INSERT INTO `token` VALUES ('12', '46', '0', 'limbah', '1');
INSERT INTO `token` VALUES ('12', '51', '0', 'salah', '1');
INSERT INTO `token` VALUES ('12', '53', '0', 'olah', '1');
INSERT INTO `token` VALUES ('12', '54', '0', 'limbah', '1');
INSERT INTO `token` VALUES ('12', '59', '0', 'masyarakat', '1');
INSERT INTO `token` VALUES ('12', '61', '0', 'buat', '1');
INSERT INTO `token` VALUES ('12', '62', '0', 'pupuk', '1');
INSERT INTO `token` VALUES ('12', '63', '0', 'kompos', '1');
INSERT INTO `token` VALUES ('12', '64', '0', 'sampah', '1');
INSERT INTO `token` VALUES ('12', '68', '0', 'guna', '1');
INSERT INTO `token` VALUES ('12', '70', '0', 'ubah', '1');
INSERT INTO `token` VALUES ('12', '72', '0', 'pupuk', '1');
INSERT INTO `token` VALUES ('12', '73', '0', 'kompos', '1');
INSERT INTO `token` VALUES ('12', '76', '0', 'guna', '1');
INSERT INTO `token` VALUES ('13', '1', '0', 'kota', '1');
INSERT INTO `token` VALUES ('13', '2', '0', 'semarang', '1');
INSERT INTO `token` VALUES ('13', '3', '0', 'milik', '1');
INSERT INTO `token` VALUES ('13', '4', '0', 'uni', '1');
INSERT INTO `token` VALUES ('13', '6', '0', 'daya', '1');
INSERT INTO `token` VALUES ('13', '7', '0', 'tarik', '1');
INSERT INTO `token` VALUES ('13', '8', '0', 'sendiri', '1');
INSERT INTO `token` VALUES ('13', '10', '0', 'letak', '1');
INSERT INTO `token` VALUES ('13', '11', '0', 'topografi', '1');
INSERT INTO `token` VALUES ('13', '13', '0', 'milik', '1');
INSERT INTO `token` VALUES ('13', '14', '0', 'wilayah', '1');
INSERT INTO `token` VALUES ('13', '15', '0', 'bukit', '1');
INSERT INTO `token` VALUES ('13', '17', '0', 'datar', '1');
INSERT INTO `token` VALUES ('13', '18', '0', 'rendah', '1');
INSERT INTO `token` VALUES ('13', '21', '0', 'milik', '1');
INSERT INTO `token` VALUES ('13', '24', '0', 'kota', '1');
INSERT INTO `token` VALUES ('13', '25', '0', 'provinsi', '1');
INSERT INTO `token` VALUES ('13', '28', '0', 'pulau', '1');
INSERT INTO `token` VALUES ('13', '29', '0', 'jawa', '1');
INSERT INTO `token` VALUES ('13', '30', '0', 'wilayah', '1');
INSERT INTO `token` VALUES ('13', '31', '0', 'kota', '1');
INSERT INTO `token` VALUES ('13', '32', '0', 'semarang', '1');
INSERT INTO `token` VALUES ('13', '34', '0', 'bukit', '1');
INSERT INTO `token` VALUES ('13', '38', '0', 'wilayah', '1');
INSERT INTO `token` VALUES ('13', '40', '0', 'milik', '1');
INSERT INTO `token` VALUES ('13', '41', '0', 'cadang', '1');
INSERT INTO `token` VALUES ('13', '42', '0', 'air', '1');
INSERT INTO `token` VALUES ('13', '43', '0', 'bersih', '1');
INSERT INTO `token` VALUES ('13', '45', '0', 'pada', '1');
INSERT INTO `token` VALUES ('13', '47', '0', 'penuh', '1');
INSERT INTO `token` VALUES ('13', '48', '0', 'butuh', '1');
INSERT INTO `token` VALUES ('13', '49', '0', 'warga', '1');
INSERT INTO `token` VALUES ('13', '50', '0', 'kota', '1');
INSERT INTO `token` VALUES ('13', '51', '0', 'semarang', '1');
INSERT INTO `token` VALUES ('13', '54', '0', 'wilayah', '1');
INSERT INTO `token` VALUES ('13', '55', '0', 'datar', '1');
INSERT INTO `token` VALUES ('13', '56', '0', 'rendah', '1');
INSERT INTO `token` VALUES ('13', '61', '0', 'wilayah', '1');
INSERT INTO `token` VALUES ('13', '62', '0', 'pesisir', '1');
INSERT INTO `token` VALUES ('13', '64', '0', 'pusat', '1');
INSERT INTO `token` VALUES ('13', '65', '0', 'ekonomi', '1');
INSERT INTO `token` VALUES ('13', '66', '0', 'kota', '1');
INSERT INTO `token` VALUES ('13', '67', '0', 'wilayah', '1');
INSERT INTO `token` VALUES ('13', '68', '0', 'bukit', '1');
INSERT INTO `token` VALUES ('13', '70', '0', 'simpan', '1');
INSERT INTO `token` VALUES ('13', '72', '0', 'sedia', '1');
INSERT INTO `token` VALUES ('13', '73', '0', 'sumberdaya', '1');
INSERT INTO `token` VALUES ('13', '74', '0', 'air', '1');
INSERT INTO `token` VALUES ('13', '75', '0', 'bersih', '1');
INSERT INTO `token` VALUES ('13', '77', '0', 'kota', '1');
INSERT INTO `token` VALUES ('13', '78', '0', 'semarang', '1');
INSERT INTO `token` VALUES ('13', '82', '0', 'kembang', '1');
INSERT INTO `token` VALUES ('13', '84', '0', 'pusat', '1');
INSERT INTO `token` VALUES ('13', '85', '0', 'giat', '1');
INSERT INTO `token` VALUES ('13', '86', '0', 'ekonomi', '1');
INSERT INTO `token` VALUES ('13', '88', '0', 'kota', '1');
INSERT INTO `token` VALUES ('13', '89', '0', 'semarang', '1');
INSERT INTO `token` VALUES ('14', '1', '0', 'manfaat', '1');
INSERT INTO `token` VALUES ('14', '2', '0', 'jaga', '1');
INSERT INTO `token` VALUES ('14', '3', '0', 'bersih', '1');
INSERT INTO `token` VALUES ('14', '7', '0', 'iman', '1');
INSERT INTO `token` VALUES ('14', '9', '0', 'salah', '1');
INSERT INTO `token` VALUES ('14', '11', '0', 'hadits', '1');
INSERT INTO `token` VALUES ('14', '14', '0', 'jadi', '1');
INSERT INTO `token` VALUES ('14', '15', '0', 'pedoman', '1');
INSERT INTO `token` VALUES ('14', '17', '0', 'umat', '1');
INSERT INTO `token` VALUES ('14', '18', '0', 'islam', '1');
INSERT INTO `token` VALUES ('14', '19', '0', 'mana', '1');
INSERT INTO `token` VALUES ('14', '22', '0', 'iman', '1');
INSERT INTO `token` VALUES ('14', '26', '0', 'pelihara', '1');
INSERT INTO `token` VALUES ('14', '27', '0', 'bersih', '1');
INSERT INTO `token` VALUES ('14', '28', '0', 'lingkung', '1');
INSERT INTO `token` VALUES ('14', '30', '0', 'bersih', '1');
INSERT INTO `token` VALUES ('14', '32', '0', 'damba', '1');
INSERT INTO `token` VALUES ('14', '34', '0', 'warga', '1');
INSERT INTO `token` VALUES ('14', '36', '0', 'bersih', '1');
INSERT INTO `token` VALUES ('14', '39', '0', 'jalan', '1');
INSERT INTO `token` VALUES ('14', '40', '0', 'aktivitas', '1');
INSERT INTO `token` VALUES ('14', '41', '0', 'hari', '1');
INSERT INTO `token` VALUES ('14', '44', '0', 'aman', '1');
INSERT INTO `token` VALUES ('14', '46', '0', 'nyaman', '1');
INSERT INTO `token` VALUES ('15', '1', '0', 'sejarah', '1');
INSERT INTO `token` VALUES ('15', '2', '0', 'cetus', '1');
INSERT INTO `token` VALUES ('15', '3', '0', 'tanggal', '1');
INSERT INTO `token` VALUES ('15', '5', '0', 'putus', '1');
INSERT INTO `token` VALUES ('15', '7', '0', 'international', '1');
INSERT INTO `token` VALUES ('15', '8', '0', 'tiger', '1');
INSERT INTO `token` VALUES ('15', '9', '0', 'summit', '1');
INSERT INTO `token` VALUES ('15', '11', '0', 'konferensi', '1');
INSERT INTO `token` VALUES ('15', '12', '0', 'tingkat', '1');
INSERT INTO `token` VALUES ('15', '14', '0', 'ktt', '1');
INSERT INTO `token` VALUES ('15', '15', '0', 'harimau', '1');
INSERT INTO `token` VALUES ('15', '16', '0', 'internasional', '1');
INSERT INTO `token` VALUES ('15', '20', '0', 'st', '1');
INSERT INTO `token` VALUES ('15', '21', '0', 'petersburg', '1');
INSERT INTO `token` VALUES ('15', '22', '0', 'rusia', '1');
INSERT INTO `token` VALUES ('15', '23', '0', 'indonesia', '1');
INSERT INTO `token` VALUES ('15', '27', '0', 'momen', '1');
INSERT INTO `token` VALUES ('16', '1', '0', 'dunia', '1');
INSERT INTO `token` VALUES ('16', '2', '0', 'teliti', '1');
INSERT INTO `token` VALUES ('16', '3', '0', 'aktivitas', '1');
INSERT INTO `token` VALUES ('16', '4', '0', 'ilmiah', '1');
INSERT INTO `token` VALUES ('16', '6', '0', 'rumit', '1');
INSERT INTO `token` VALUES ('16', '8', '0', 'paham', '1');
INSERT INTO `token` VALUES ('16', '13', '0', 'urus', '1');
INSERT INTO `token` VALUES ('16', '18', '0', 'kes', '1');
INSERT INTO `token` VALUES ('16', '19', '0', 'sulit', '1');
INSERT INTO `token` VALUES ('16', '21', '0', 'habis', '1');
INSERT INTO `token` VALUES ('16', '24', '0', 'teliti', '1');
INSERT INTO `token` VALUES ('16', '28', '0', 'langsung', '1');
INSERT INTO `token` VALUES ('16', '29', '0', 'hidup', '1');
INSERT INTO `token` VALUES ('16', '30', '0', 'manusia', '1');
INSERT INTO `token` VALUES ('17', '1', '0', 'salah', '1');
INSERT INTO `token` VALUES ('17', '3', '0', 'hikmah', '1');
INSERT INTO `token` VALUES ('17', '4', '0', 'balik', '1');
INSERT INTO `token` VALUES ('17', '5', '0', 'pandemi', '1');
INSERT INTO `token` VALUES ('17', '6', '0', 'covid', '1');
INSERT INTO `token` VALUES ('17', '8', '0', 'gencar', '1');
INSERT INTO `token` VALUES ('17', '9', '0', 'guna', '1');
INSERT INTO `token` VALUES ('17', '11', '0', 'aplikasi', '1');
INSERT INTO `token` VALUES ('17', '12', '0', 'bas', '1');
INSERT INTO `token` VALUES ('17', '13', '0', 'daring', '1');
INSERT INTO `token` VALUES ('17', '14', '0', 'menteri', '1');
INSERT INTO `token` VALUES ('17', '15', '0', 'komunikasi', '1');
INSERT INTO `token` VALUES ('17', '17', '0', 'informatika', '1');
INSERT INTO `token` VALUES ('17', '18', '0', 'kemkominfo', '1');
INSERT INTO `token` VALUES ('17', '19', '0', 'catat', '1');
INSERT INTO `token` VALUES ('17', '20', '0', 'guna', '1');
INSERT INTO `token` VALUES ('17', '21', '0', 'aplikasi', '1');
INSERT INTO `token` VALUES ('17', '22', '0', 'daring', '1');
INSERT INTO `token` VALUES ('17', '24', '0', 'persen', '1');
INSERT INTO `token` VALUES ('17', '26', '0', 'covid', '1');
INSERT INTO `token` VALUES ('18', '1', '0', 'dorong', '1');
INSERT INTO `token` VALUES ('18', '2', '0', 'publik', '1');
INSERT INTO `token` VALUES ('18', '3', '0', 'jaga', '1');
INSERT INTO `token` VALUES ('18', '4', '0', 'lingkung', '1');
INSERT INTO `token` VALUES ('18', '7', '0', 'tantang', '1');
INSERT INTO `token` VALUES ('18', '10', '0', 'hadap', '1');
INSERT INTO `token` VALUES ('18', '12', '0', 'lingkung', '1');
INSERT INTO `token` VALUES ('18', '13', '0', 'hidup', '1');
INSERT INTO `token` VALUES ('18', '14', '0', 'dunia', '1');
INSERT INTO `token` VALUES ('18', '17', '0', 'konsisten', '1');
INSERT INTO `token` VALUES ('18', '18', '0', 'diperangati', '1');
INSERT INTO `token` VALUES ('18', '20', '0', 'juni', '1');
INSERT INTO `token` VALUES ('18', '21', '0', 'lansir', '1');
INSERT INTO `token` VALUES ('18', '23', '0', 'laman', '1');
INSERT INTO `token` VALUES ('18', '24', '0', 'resmi', '1');
INSERT INTO `token` VALUES ('18', '25', '0', 'sabtu', '1');
INSERT INTO `token` VALUES ('18', '26', '0', 'keanekaragaman', '1');
INSERT INTO `token` VALUES ('18', '27', '0', 'hayati', '1');
INSERT INTO `token` VALUES ('18', '30', '0', 'fokus', '1');
INSERT INTO `token` VALUES ('18', '32', '0', 'angkat', '1');
INSERT INTO `token` VALUES ('19', '1', '0', 'peran', '1');
INSERT INTO `token` VALUES ('19', '2', '0', 'orang', '1');
INSERT INTO `token` VALUES ('19', '3', '0', 'tua', '1');
INSERT INTO `token` VALUES ('19', '5', '0', 'didik', '1');
INSERT INTO `token` VALUES ('19', '6', '0', 'anak', '1');
INSERT INTO `token` VALUES ('19', '8', '0', 'nomor', '1');
INSERT INTO `token` VALUES ('19', '11', '0', 'anak', '1');
INSERT INTO `token` VALUES ('19', '12', '0', 'kenal', '1');
INSERT INTO `token` VALUES ('19', '13', '0', 'dunia', '1');
INSERT INTO `token` VALUES ('19', '15', '0', 'orang', '1');
INSERT INTO `token` VALUES ('19', '19', '0', 'kenal', '1');
INSERT INTO `token` VALUES ('19', '21', '0', 'ayah', '1');
INSERT INTO `token` VALUES ('19', '23', '0', 'ibu', '1');
INSERT INTO `token` VALUES ('19', '24', '0', 'anak', '1');
INSERT INTO `token` VALUES ('19', '27', '0', 'tiru', '1');
INSERT INTO `token` VALUES ('19', '33', '0', 'orang', '1');
INSERT INTO `token` VALUES ('19', '34', '0', 'tua', '1');
INSERT INTO `token` VALUES ('19', '38', '0', 'dengar', '1');
INSERT INTO `token` VALUES ('19', '40', '0', 'lihat', '1');
INSERT INTO `token` VALUES ('19', '44', '0', 'tangkap', '1');
INSERT INTO `token` VALUES ('19', '46', '0', 'simpan', '1');
INSERT INTO `token` VALUES ('19', '48', '0', 'memori', '1');
INSERT INTO `token` VALUES ('19', '52', '0', 'ajar', '1');
INSERT INTO `token` VALUES ('19', '53', '0', 'bicara', '1');
INSERT INTO `token` VALUES ('19', '54', '0', 'orang', '1');
INSERT INTO `token` VALUES ('19', '55', '0', 'tua', '1');
INSERT INTO `token` VALUES ('19', '57', '0', 'guru', '1');
INSERT INTO `token` VALUES ('19', '58', '0', 'bagi', '1');
INSERT INTO `token` VALUES ('20', '2', '0', 'upaya', '1');
INSERT INTO `token` VALUES ('20', '4', '0', 'cegah', '1');
INSERT INTO `token` VALUES ('20', '5', '0', 'pandemi', '1');
INSERT INTO `token` VALUES ('20', '6', '0', 'covid', '1');
INSERT INTO `token` VALUES ('20', '7', '0', 'perintah', '1');
INSERT INTO `token` VALUES ('20', '8', '0', 'keluar', '1');
INSERT INTO `token` VALUES ('20', '9', '0', 'bijak', '1');
INSERT INTO `token` VALUES ('20', '11', '0', 'sekolah', '1');
INSERT INTO `token` VALUES ('20', '12', '0', 'sekolah', '1');
INSERT INTO `token` VALUES ('20', '14', '0', 'siswa', '1');
INSERT INTO `token` VALUES ('20', '16', '0', 'ajar', '1');
INSERT INTO `token` VALUES ('20', '18', '0', 'rumah', '1');
INSERT INTO `token` VALUES ('20', '20', '0', 'maret', '1');
INSERT INTO `token` VALUES ('20', '21', '0', 'sekolah', '1');
INSERT INTO `token` VALUES ('20', '22', '0', 'terap', '1');
INSERT INTO `token` VALUES ('20', '23', '0', 'metode', '1');
INSERT INTO `token` VALUES ('20', '24', '0', 'ajar', '1');
INSERT INTO `token` VALUES ('20', '25', '0', 'siswa', '1');
INSERT INTO `token` VALUES ('20', '27', '0', 'daring', '1');
INSERT INTO `token` VALUES ('20', '29', '0', 'efektif', '1');
INSERT INTO `token` VALUES ('20', '30', '0', 'ajar', '1');
INSERT INTO `token` VALUES ('20', '31', '0', 'daring', '1');
INSERT INTO `token` VALUES ('21', '1', '0', 'dampak', '1');
INSERT INTO `token` VALUES ('21', '2', '0', 'pandemik', '1');
INSERT INTO `token` VALUES ('21', '4', '0', 'sistem', '1');
INSERT INTO `token` VALUES ('21', '5', '0', 'didik', '1');
INSERT INTO `token` VALUES ('21', '11', '0', 'masuk', '1');
INSERT INTO `token` VALUES ('21', '13', '0', 'era', '1');
INSERT INTO `token` VALUES ('21', '14', '0', 'revolusi', '1');
INSERT INTO `token` VALUES ('21', '15', '0', 'industry', '1');
INSERT INTO `token` VALUES ('21', '16', '0', 'era', '1');
INSERT INTO `token` VALUES ('21', '17', '0', 'serba', '1');
INSERT INTO `token` VALUES ('21', '18', '0', 'digital', '1');
INSERT INTO `token` VALUES ('21', '24', '0', 'urus', '1');
INSERT INTO `token` VALUES ('21', '25', '0', 'dapur', '1');
INSERT INTO `token` VALUES ('21', '27', '0', 'urus', '1');
INSERT INTO `token` VALUES ('21', '28', '0', 'didik', '1');
INSERT INTO `token` VALUES ('21', '30', '0', 'layan', '1');
INSERT INTO `token` VALUES ('21', '35', '0', 'bidang', '1');
INSERT INTO `token` VALUES ('21', '36', '0', 'transformasi', '1');
INSERT INTO `token` VALUES ('21', '38', '0', 'serba', '1');
INSERT INTO `token` VALUES ('21', '39', '0', 'online', '1');
INSERT INTO `token` VALUES ('21', '44', '0', 'nama', '1');
INSERT INTO `token` VALUES ('21', '45', '0', 'susah', '1');
INSERT INTO `token` VALUES ('21', '47', '0', 'sulit', '1');
INSERT INTO `token` VALUES ('21', '49', '0', 'teknologi', '1');
INSERT INTO `token` VALUES ('21', '50', '0', 'tawar', '1');
INSERT INTO `token` VALUES ('21', '51', '0', 'fasilitas', '1');
INSERT INTO `token` VALUES ('21', '53', '0', 'serba', '1');
INSERT INTO `token` VALUES ('21', '54', '0', 'mudah', '1');
INSERT INTO `token` VALUES ('21', '59', '0', 'tulis', '1');
INSERT INTO `token` VALUES ('21', '60', '0', 'duduk', '1');
INSERT INTO `token` VALUES ('21', '62', '0', 'narasumber', '1');
INSERT INTO `token` VALUES ('21', '64', '0', 'fasilitator', '1');
INSERT INTO `token` VALUES ('21', '67', '0', 'tulis', '1');
INSERT INTO `token` VALUES ('21', '68', '0', 'mudah', '1');
INSERT INTO `token` VALUES ('21', '70', '0', 'hadir', '1');
INSERT INTO `token` VALUES ('21', '71', '0', 'teknologi', '1');
INSERT INTO `token` VALUES ('21', '74', '0', 'arsitek', '1');
INSERT INTO `token` VALUES ('21', '76', '0', 'bidang', '1');
INSERT INTO `token` VALUES ('21', '77', '0', 'didik', '1');
INSERT INTO `token` VALUES ('21', '79', '0', 'cepat', '1');
INSERT INTO `token` VALUES ('21', '80', '0', 'adaptasi', '1');
INSERT INTO `token` VALUES ('21', '82', '0', 'cepat', '1');
INSERT INTO `token` VALUES ('21', '83', '0', 'kuasa', '1');
INSERT INTO `token` VALUES ('21', '84', '0', 'ilmu', '1');
INSERT INTO `token` VALUES ('21', '85', '0', 'tahu', '1');
INSERT INTO `token` VALUES ('21', '88', '0', 'ubah', '1');
INSERT INTO `token` VALUES ('21', '89', '0', 'situasi', '1');
INSERT INTO `token` VALUES ('21', '91', '0', 'kondisi', '1');
INSERT INTO `token` VALUES ('21', '92', '0', 'widyaiswara', '1');
INSERT INTO `token` VALUES ('21', '95', '0', 'tunggu', '1');
INSERT INTO `token` VALUES ('21', '96', '0', 'jadwal', '1');
INSERT INTO `token` VALUES ('21', '97', '0', 'ajar', '1');
INSERT INTO `token` VALUES ('21', '99', '0', 'klasikal', '1');
INSERT INTO `token` VALUES ('21', '102', '0', 'tuntut', '1');
INSERT INTO `token` VALUES ('21', '105', '0', 'pro', '1');
INSERT INTO `token` VALUES ('21', '106', '0', 'aktif', '1');
INSERT INTO `token` VALUES ('21', '108', '0', 'beraktifitas', '1');
INSERT INTO `token` VALUES ('21', '110', '0', 'peran', '1');
INSERT INTO `token` VALUES ('21', '113', '0', 'rubah', '1');
INSERT INTO `token` VALUES ('21', '114', '0', 'mindset', '1');
INSERT INTO `token` VALUES ('21', '115', '0', 'pola', '1');
INSERT INTO `token` VALUES ('21', '116', '0', 'pikir', '1');
INSERT INTO `token` VALUES ('21', '119', '0', 'klasik', '1');
INSERT INTO `token` VALUES ('21', '121', '0', 'digital', '1');
INSERT INTO `token` VALUES ('21', '126', '0', 'widyaiswara', '1');
INSERT INTO `token` VALUES ('21', '127', '0', 'ahli', '1');
INSERT INTO `token` VALUES ('21', '129', '0', 'transfer', '1');
INSERT INTO `token` VALUES ('21', '130', '0', 'sikap', '1');
INSERT INTO `token` VALUES ('21', '131', '0', 'tahu', '1');
INSERT INTO `token` VALUES ('21', '133', '0', 'ahli', '1');
INSERT INTO `token` VALUES ('21', '135', '0', 'kelas', '1');
INSERT INTO `token` VALUES ('21', '137', '0', 'klasikal', '1');
INSERT INTO `token` VALUES ('21', '138', '0', 'tatap', '1');
INSERT INTO `token` VALUES ('21', '139', '0', 'muka', '1');
INSERT INTO `token` VALUES ('21', '141', '0', 'langsung', '1');
INSERT INTO `token` VALUES ('21', '144', '0', 'serta', '1');
INSERT INTO `token` VALUES ('21', '146', '0', 'materi', '1');
INSERT INTO `token` VALUES ('21', '148', '0', 'bentuk', '1');
INSERT INTO `token` VALUES ('21', '149', '0', 'slide', '1');
INSERT INTO `token` VALUES ('21', '151', '0', 'salam', '1');
INSERT INTO `token` VALUES ('21', '153', '0', 'langsung', '1');
INSERT INTO `token` VALUES ('21', '156', '0', 'langsung', '1');
INSERT INTO `token` VALUES ('21', '159', '0', 'senyum', '1');
INSERT INTO `token` VALUES ('21', '161', '0', 'tawa', '1');
INSERT INTO `token` VALUES ('21', '163', '0', 'canda', '1');
INSERT INTO `token` VALUES ('21', '165', '0', 'alami', '1');
INSERT INTO `token` VALUES ('22', '1', '0', 'indonesia', '1');
INSERT INTO `token` VALUES ('22', '4', '0', 'negara', '1');
INSERT INTO `token` VALUES ('22', '6', '0', 'dunia', '1');
INSERT INTO `token` VALUES ('22', '10', '0', 'alami', '1');
INSERT INTO `token` VALUES ('22', '11', '0', 'musibah', '1');
INSERT INTO `token` VALUES ('22', '14', '0', 'sakit', '1');
INSERT INTO `token` VALUES ('22', '16', '0', 'sebab', '1');
INSERT INTO `token` VALUES ('22', '18', '0', 'virus', '1');
INSERT INTO `token` VALUES ('22', '19', '0', 'jenis', '1');
INSERT INTO `token` VALUES ('22', '22', '0', 'kenal', '1');
INSERT INTO `token` VALUES ('22', '24', '0', 'istilah', '1');
INSERT INTO `token` VALUES ('22', '25', '0', 'covid', '1');
INSERT INTO `token` VALUES ('22', '26', '0', 'corona', '1');
INSERT INTO `token` VALUES ('22', '27', '0', 'virus', '1');
INSERT INTO `token` VALUES ('22', '28', '0', 'diseases', '1');
INSERT INTO `token` VALUES ('22', '29', '0', 'virus', '1');
INSERT INTO `token` VALUES ('22', '30', '0', 'corona', '1');
INSERT INTO `token` VALUES ('22', '32', '0', 'aktivitas', '1');
INSERT INTO `token` VALUES ('22', '33', '0', 'manusia', '1');
INSERT INTO `token` VALUES ('22', '34', '0', 'ubah', '1');
INSERT INTO `token` VALUES ('22', '35', '0', 'total', '1');
INSERT INTO `token` VALUES ('22', '38', '0', 'minggu', '1');
INSERT INTO `token` VALUES ('22', '41', '0', 'ubah', '1');
INSERT INTO `token` VALUES ('22', '46', '0', 'aspek', '1');
INSERT INTO `token` VALUES ('22', '49', '0', 'aktivitas', '1');
INSERT INTO `token` VALUES ('22', '50', '0', 'ekonomi', '1');
INSERT INTO `token` VALUES ('22', '51', '0', 'industri', '1');
INSERT INTO `token` VALUES ('22', '52', '0', 'sosial', '1');
INSERT INTO `token` VALUES ('22', '54', '0', 'didik', '1');
INSERT INTO `token` VALUES ('23', '4', '0', 'tepat', '1');
INSERT INTO `token` VALUES ('23', '5', '0', 'tanggal', '1');
INSERT INTO `token` VALUES ('23', '6', '0', 'desember', '1');
INSERT INTO `token` VALUES ('23', '7', '0', 'hasil', '1');
INSERT INTO `token` VALUES ('23', '8', '0', 'studi', '1');
INSERT INTO `token` VALUES ('23', '9', '0', 'program', '1');
INSERT INTO `token` VALUES ('23', '10', '0', 'for', '1');
INSERT INTO `token` VALUES ('23', '11', '0', 'international', '1');
INSERT INTO `token` VALUES ('23', '12', '0', 'student', '1');
INSERT INTO `token` VALUES ('23', '13', '0', 'assessment', '1');
INSERT INTO `token` VALUES ('23', '14', '0', 'pisa', '1');
INSERT INTO `token` VALUES ('23', '16', '0', 'rilis', '1');
INSERT INTO `token` VALUES ('23', '17', '0', 'pisa', '1');
INSERT INTO `token` VALUES ('23', '20', '0', 'sistem', '1');
INSERT INTO `token` VALUES ('23', '21', '0', 'uji', '1');
INSERT INTO `token` VALUES ('23', '25', '0', 'organization', '1');
INSERT INTO `token` VALUES ('23', '26', '0', 'for', '1');
INSERT INTO `token` VALUES ('23', '27', '0', 'economics', '1');
INSERT INTO `token` VALUES ('23', '28', '0', 'cooperation', '1');
INSERT INTO `token` VALUES ('23', '29', '0', 'and', '1');
INSERT INTO `token` VALUES ('23', '30', '0', 'development', '1');
INSERT INTO `token` VALUES ('23', '31', '0', 'oecd', '1');
INSERT INTO `token` VALUES ('23', '33', '0', 'ukur', '1');
INSERT INTO `token` VALUES ('23', '34', '0', 'kualitas', '1');
INSERT INTO `token` VALUES ('23', '35', '0', 'hasil', '1');
INSERT INTO `token` VALUES ('23', '36', '0', 'didik', '1');
INSERT INTO `token` VALUES ('23', '38', '0', 'negara', '1');
INSERT INTO `token` VALUES ('23', '39', '0', 'negara', '1');
INSERT INTO `token` VALUES ('23', '42', '0', 'dunia', '1');
INSERT INTO `token` VALUES ('23', '47', '0', 'pisa', '1');
INSERT INTO `token` VALUES ('23', '49', '0', 'tes', '1');
INSERT INTO `token` VALUES ('23', '50', '0', 'mampu', '1');
INSERT INTO `token` VALUES ('23', '51', '0', 'baca', '1');
INSERT INTO `token` VALUES ('23', '52', '0', 'matematika', '1');
INSERT INTO `token` VALUES ('23', '54', '0', 'sains', '1');
INSERT INTO `token` VALUES ('23', '56', '0', 'siswa', '1');
INSERT INTO `token` VALUES ('23', '57', '0', 'usia', '1');
INSERT INTO `token` VALUES ('23', '60', '0', 'pilih', '1');
INSERT INTO `token` VALUES ('23', '62', '0', 'acak', '1');
INSERT INTO `token` VALUES ('23', '65', '0', 'negara', '1');
INSERT INTO `token` VALUES ('23', '66', '0', 'negara', '1');
INSERT INTO `token` VALUES ('23', '68', '0', 'uji', '1');
INSERT INTO `token` VALUES ('23', '72', '0', 'negara', '1');
INSERT INTO `token` VALUES ('23', '76', '0', 'studi', '1');
INSERT INTO `token` VALUES ('23', '81', '0', 'ikut', '1');
INSERT INTO `token` VALUES ('23', '83', '0', 'negara', '1');
INSERT INTO `token` VALUES ('24', '1', '0', 'generasi', '1');
INSERT INTO `token` VALUES ('24', '2', '0', 'muda', '1');
INSERT INTO `token` VALUES ('24', '4', '0', 'aset', '1');
INSERT INTO `token` VALUES ('24', '7', '0', 'bawa', '1');
INSERT INTO `token` VALUES ('24', '8', '0', 'maju', '1');
INSERT INTO `token` VALUES ('24', '10', '0', 'bangsa', '1');
INSERT INTO `token` VALUES ('24', '11', '0', 'dasar', '1');
INSERT INTO `token` VALUES ('24', '12', '0', 'hasil', '1');
INSERT INTO `token` VALUES ('24', '13', '0', 'survei', '1');
INSERT INTO `token` VALUES ('24', '14', '0', 'duduk', '1');
INSERT INTO `token` VALUES ('24', '16', '0', 'sensus', '1');
INSERT INTO `token` VALUES ('24', '17', '0', 'supas', '1');
INSERT INTO `token` VALUES ('24', '19', '0', 'duduk', '1');
INSERT INTO `token` VALUES ('24', '20', '0', 'indonesia', '1');
INSERT INTO `token` VALUES ('24', '22', '0', 'prediksi', '1');
INSERT INTO `token` VALUES ('24', '23', '0', 'capai', '1');
INSERT INTO `token` VALUES ('24', '24', '0', 'juta', '1');
INSERT INTO `token` VALUES ('24', '25', '0', 'jiwa', '1');
INSERT INTO `token` VALUES ('24', '30', '0', 'juta', '1');
INSERT INTO `token` VALUES ('24', '31', '0', 'jiwa', '1');
INSERT INTO `token` VALUES ('24', '32', '0', 'perempuan', '1');
INSERT INTO `token` VALUES ('24', '34', '0', 'juta', '1');
INSERT INTO `token` VALUES ('24', '35', '0', 'jiwa', '1');
INSERT INTO `token` VALUES ('24', '36', '0', 'laki', '1');
INSERT INTO `token` VALUES ('24', '37', '0', 'laki', '1');
INSERT INTO `token` VALUES ('24', '40', '0', 'duduk', '1');
INSERT INTO `token` VALUES ('24', '43', '0', 'capai', '1');
INSERT INTO `token` VALUES ('24', '44', '0', 'juta', '1');
INSERT INTO `token` VALUES ('24', '45', '0', 'jiwa', '1');
INSERT INTO `token` VALUES ('24', '49', '0', 'tambah', '1');
INSERT INTO `token` VALUES ('24', '50', '0', 'juta', '1');
INSERT INTO `token` VALUES ('24', '51', '0', 'jiwa', '1');
INSERT INTO `token` VALUES ('25', '1', '0', 'yup', '1');
INSERT INTO `token` VALUES ('25', '2', '0', 'awal', '1');
INSERT INTO `token` VALUES ('25', '5', '0', 'bumi', '1');
INSERT INTO `token` VALUES ('25', '6', '0', 'merestart', '1');
INSERT INTO `token` VALUES ('25', '9', '0', 'covid', '1');
INSERT INTO `token` VALUES ('25', '10', '0', 'salah', '1');
INSERT INTO `token` VALUES ('25', '11', '0', 'satu', '1');
INSERT INTO `token` VALUES ('25', '12', '0', 'kualitas', '1');
INSERT INTO `token` VALUES ('25', '13', '0', 'udara', '1');
INSERT INTO `token` VALUES ('25', '16', '0', 'kota', '1');
INSERT INTO `token` VALUES ('25', '17', '0', 'dunia', '1');
INSERT INTO `token` VALUES ('25', '22', '0', 'media', '1');
INSERT INTO `token` VALUES ('25', '23', '0', 'sosial', '1');
INSERT INTO `token` VALUES ('25', '24', '0', 'salah', '1');
INSERT INTO `token` VALUES ('25', '25', '0', 'satu', '1');
INSERT INTO `token` VALUES ('25', '26', '0', 'nasa', '1');
INSERT INTO `token` VALUES ('25', '27', '0', 'bagi', '1');
INSERT INTO `token` VALUES ('25', '28', '0', 'hasil', '1');
INSERT INTO `token` VALUES ('25', '29', '0', 'citra', '1');
INSERT INTO `token` VALUES ('25', '30', '0', 'satelit', '1');
INSERT INTO `token` VALUES ('25', '33', '0', 'udara', '1');
INSERT INTO `token` VALUES ('25', '35', '0', 'china', '1');
INSERT INTO `token` VALUES ('25', '39', '0', 'wabah', '1');
INSERT INTO `token` VALUES ('25', '40', '0', 'covid', '1');
INSERT INTO `token` VALUES ('25', '41', '0', 'landa', '1');
INSERT INTO `token` VALUES ('25', '42', '0', 'china', '1');

SET FOREIGN_KEY_CHECKS = 1;
